/**
 * The roster (gamification spec §13) — all 22 birds, every one a real species.
 *
 * Prices and tiers are the spec's design targets; the signature move is what
 * the tier actually buys (§09). Six species migrate — the only birds whose
 * perch is ever empty. The Skylark is the starter: she arrives with the kid on
 * day one and is never bought.
 *
 * Field Guide rules (§07): entries are about the REAL bird and nothing else.
 * Four facts, always the same four, and the conservation line ends hopeful in
 * every single entry. All facts here are true of the species.
 *
 * Art is NOT final: every species renders through BirdSprite's named
 * placeholder slot (portrait, three scales, idle pose, tier behaviour rig) so
 * commissioned art drops in without layout changes.
 *
 * `seasons` — quarters the bird is present (null = resident all year).
 * `perchTypes` — which named perch kinds suit the species (perches.js).
 */

export const TIERS = {
  common: { id: "common", label: "Common", tag: "good company" },
  uncommon: { id: "uncommon", label: "Uncommon", tag: "has a trick" },
  rare: { id: "rare", label: "Rare", tag: "puts on a show" },
  legendary: { id: "legendary", label: "One of a kind", tag: "one of a kind" },
};

export const SPECIES = [
  {
    id: "skylark",
    name: "Skylark",
    latin: "Alauda arvensis",
    tier: "common",
    price: null,
    starter: true,
    pronoun: "she",
    seasons: null,
    moveLine: "Arrives with you on day one. Sings on the wing.",
    signature: null,
    perchTypes: ["ground", "fencePost", "lowBranch"],
    presetNames: ["Sky", "Pip", "Lark", "Breeze", "Sunny", "Trill"],
    wow: "She sings for minutes at a time while flying so high you can hardly see her.",
    facts: {
      howBig: "About as long as a pencil",
      eats: "Seeds and small insects, found on foot in the grass",
      lives: "Open meadows and farm fields across Europe and Asia",
      doing: "Still singing over meadows everywhere — farmers now leave grassy strips just for her",
    },
    callCaption: "♪ a long, bubbling song that never seems to stop",
  },
  {
    id: "houseFinch",
    name: "House Finch",
    latin: "Haemorhous mexicanus",
    tier: "common",
    price: 15,
    pronoun: "he",
    seasons: null,
    moveLine: "Idle and feeder loops.",
    signature: null,
    perchTypes: ["highBranch", "lowBranch", "fencePost"],
    presetNames: ["Rusty", "Berry", "Chip", "Rosie", "Scout", "Pepper"],
    wow: "His red feathers come from the berries he eats — more berries, redder feathers.",
    facts: {
      howBig: "About as long as your hand",
      eats: "Seeds, buds and berries — he almost never eats bugs",
      lives: "Towns and backyards right across North America",
      doing: "Thriving — one of the most common feeder birds on the continent",
    },
    callCaption: "♪ a cheerful, jumbled warble",
  },
  {
    id: "mourningDove",
    name: "Mourning Dove",
    latin: "Zenaida macroura",
    tier: "common",
    price: 16,
    pronoun: "she",
    seasons: null,
    moveLine: "Idle and ground loops.",
    signature: null,
    perchTypes: ["ground", "fencePost", "lowBranch"],
    presetNames: ["Coo", "Willow", "Dusty", "Pearl", "Mo", "Ash"],
    wow: "Her wings whistle when she takes off — that sound is made by her feathers, not her voice.",
    facts: {
      howBig: "About as long as a school ruler",
      eats: "Seeds, hoovered up off the ground and stored in her chest for later",
      lives: "Open country, farms and backyards across North America",
      doing: "Thriving — there are hundreds of millions of mourning doves",
    },
    callCaption: "♪ coo-OO-oo, soft and low",
  },
  {
    id: "chickadee",
    name: "Black-capped Chickadee",
    latin: "Poecile atricapillus",
    tier: "common",
    price: 18,
    pronoun: "she",
    seasons: null,
    moveLine: "Idle and feeder loops.",
    signature: null,
    perchTypes: ["highBranch", "lowBranch", "fencePost"],
    presetNames: ["Dee", "Boots", "Ziggy", "Maple", "Tiny", "Nib"],
    wow: "She hides thousands of seeds for winter — and remembers where nearly every one is.",
    facts: {
      howBig: "Smaller than your fist",
      eats: "Seeds and insects, taken one at a time and carried off to eat",
      lives: "Woods and backyards across the northern half of North America",
      doing: "Thriving — chickadees cheer up feeders all winter long",
    },
    callCaption: "♪ chick-a-dee-dee-dee",
  },
  {
    id: "houseWren",
    name: "House Wren",
    latin: "Troglodytes aedon",
    tier: "common",
    price: 18,
    pronoun: "he",
    seasons: null,
    moveLine: "Idle and dust-patch loops.",
    signature: null,
    perchTypes: ["lowBranch", "nestBox", "log"],
    presetNames: ["Twig", "Bramble", "Jasper", "Ivy", "Zip", "Nutmeg"],
    wow: "He can sing hundreds of songs in a single morning without running out.",
    facts: {
      howBig: "About as big as a plum",
      eats: "Insects and spiders, hunted in every corner of the garden",
      lives: "Gardens and woodland edges from Canada all the way to South America",
      doing: "Thriving — one of the most widespread songbirds in the Americas",
    },
    callCaption: "♪ a fast, bubbling chatter",
  },
  {
    id: "robin",
    name: "American Robin",
    latin: "Turdus migratorius",
    tier: "common",
    price: 20,
    pronoun: "she",
    seasons: null,
    moveLine: "Idle and bath loops.",
    signature: null,
    perchTypes: ["ground", "lowBranch", "fencePost"],
    presetNames: ["Red", "Clover", "Hop", "Ruby", "Worm", "June"],
    wow: "She tilts her head to one side to spot worms moving under the grass.",
    facts: {
      howBig: "About as long as a school ruler",
      eats: "Worms in the morning, berries in the afternoon",
      lives: "Lawns, parks and forests across nearly all of North America",
      doing: "Thriving — for many families the robin is the first sign of spring",
    },
    callCaption: "♪ cheerily, cheer-up, cheer-up!",
  },
  {
    id: "junco",
    name: "Dark-eyed Junco",
    latin: "Junco hyemalis",
    tier: "common",
    price: 20,
    pronoun: "he",
    seasons: ["winter"],
    moveLine: "Idle and ground loops.",
    signature: null,
    perchTypes: ["ground", "log", "lowBranch"],
    presetNames: ["Frost", "Pebble", "Smoky", "Flick", "Winter", "Slate"],
    wow: "People call him the snowbird — he arrives in backyards with the first snow.",
    facts: {
      howBig: "About as big as a tennis ball",
      eats: "Small seeds, picked off the ground with little two-footed hops",
      lives: "Summers in northern forests, winters in backyards across the United States",
      doing: "Doing OK — juncos are among the most numerous birds on the continent",
    },
    callCaption: "♪ a light, ringing trill",
  },
  {
    id: "cardinal",
    name: "Northern Cardinal",
    latin: "Cardinalis cardinalis",
    tier: "common",
    price: 22,
    pronoun: "she",
    seasons: null,
    moveLine: "Idle and feeder loops.",
    signature: null,
    perchTypes: ["lowBranch", "highBranch", "fencePost"],
    presetNames: ["Scarlet", "Poppy", "Ember", "Holly", "Crest", "Cherry"],
    wow: "Cardinals are one of the few songbirds where the female sings too — often from the nest.",
    facts: {
      howBig: "About as long as a school ruler",
      eats: "Big seeds that her heavy orange beak can crack",
      lives: "Thickets and backyards across the eastern half of North America",
      doing: "Thriving — more cardinals now than fifty years ago, and spreading north",
    },
    callCaption: "♪ birdie-birdie-birdie, whoit whoit!",
  },
  {
    id: "downyWoodpecker",
    name: "Downy Woodpecker",
    latin: "Dryobates pubescens",
    tier: "uncommon",
    price: 40,
    pronoun: "he",
    seasons: null,
    moveLine: "Drums the trunk — the sound carries across the zone.",
    signature: { id: "drum", line: "Drums the trunk — the sound carries across the zone." },
    perchTypes: ["trunkHollow", "highBranch", "log"],
    presetNames: ["Tap", "Knock", "Chisel", "Morse", "Rat-a-tat", "Woody"],
    wow: "He drums on trees to talk — each drumroll is a message other woodpeckers understand.",
    facts: {
      howBig: "About as long as a pencil — the smallest woodpecker in North America",
      eats: "Insects tucked inside tree bark, found by tapping and listening",
      lives: "Woods, parks and backyards across most of North America",
      doing: "Thriving — happy wherever there are trees, even in the middle of cities",
    },
    callCaption: "♪ a sharp pik! and a rolling drum",
  },
  {
    id: "goldfinch",
    name: "American Goldfinch",
    latin: "Spinus tristis",
    tier: "uncommon",
    price: 42,
    pronoun: "he",
    seasons: null,
    moveLine: "Bounces through the air in a deep, looping flight line.",
    signature: { id: "bounceFlight", line: "Bounces through the air in a deep, looping flight line." },
    perchTypes: ["highBranch", "lowBranch", "fencePost"],
    presetNames: ["Lemon", "Dandy", "Goldie", "Bounce", "Sol", "Buttercup"],
    wow: "He turns bright yellow every spring and quiet grey-brown every winter — same bird, new coat.",
    facts: {
      howBig: "Smaller than your fist",
      eats: "Seeds and almost nothing else — one of the strictest vegetarians of any bird",
      lives: "Weedy fields and gardens across most of North America",
      doing: "Thriving — plant one sunflower and he will probably find it",
    },
    callCaption: "♪ po-ta-to-chip! sung in flight, one note per bounce",
  },
  {
    id: "blueJay",
    name: "Blue Jay",
    latin: "Cyanocitta cristata",
    tier: "uncommon",
    price: 45,
    pronoun: "she",
    seasons: null,
    moveLine: "Screams like a hawk and the small birds duck.",
    signature: { id: "hawkScream", line: "Screams like a hawk and the small birds duck." },
    perchTypes: ["highBranch", "lowBranch", "fencePost"],
    presetNames: ["Jaybird, Jr.", "Indigo", "Echo", "Sassy", "Azure", "Acorn"],
    wow: "She copies a hawk's scream to scare other birds off the feeder.",
    facts: {
      howBig: "About as long as your shoe",
      eats: "Acorns — she plants oaks by accident",
      lives: "Oak woods and back gardens, right across the east",
      doing: "Thriving — more jays now than fifty years ago",
    },
    callCaption: "♪ jay! jay! — and sometimes a perfect hawk scream",
  },
  {
    id: "hummingbird",
    name: "Ruby-throated Hummingbird",
    latin: "Archilochus colubris",
    tier: "uncommon",
    price: 46,
    pronoun: "he",
    seasons: ["spring", "summer", "autumn"],
    moveLine: "Hangs still at a flower, then vanishes sideways.",
    signature: { id: "hoverVanish", line: "Hangs still at a flower, then vanishes sideways." },
    perchTypes: ["highBranch", "lowBranch"],
    presetNames: ["Zoom", "Blur", "Jewel", "Zippy", "Flash", "Hum"],
    wow: "His wings beat about fifty times every second — that hum you hear IS his wings.",
    facts: {
      howBig: "Not much bigger than your thumb",
      eats: "Flower nectar, plus tiny insects for protein",
      lives: "Summers in eastern North America; flies non-stop across the Gulf of Mexico to winter",
      doing: "Doing OK — millions make that unbelievable trip every single year",
    },
    callCaption: "♪ a squeaky chitter over a soft wing-hum",
  },
  {
    id: "kingfisher",
    name: "Belted Kingfisher",
    latin: "Megaceryle alcyon",
    tier: "uncommon",
    price: 48,
    pronoun: "she",
    seasons: null,
    moveLine: "Dives at the pond and comes up wet.",
    signature: { id: "dive", line: "Dives at the pond and comes up wet." },
    perchTypes: ["pondEdge", "lowBranch", "fencePost"],
    presetNames: ["Splash", "Halcyon", "Ripple", "Plunge", "Belt", "Azula"],
    wow: "She digs a tunnel nest in a stream bank — sometimes two metres deep.",
    facts: {
      howBig: "About as long as a school ruler, with a head too big for her body",
      eats: "Small fish, caught by diving headfirst from a hover",
      lives: "Rivers, ponds and coastlines across nearly all of North America",
      doing: "Doing OK — wherever water is clean enough to see fish, she is there",
    },
    callCaption: "♪ a loud, rattling laugh flying up the stream",
  },
  {
    id: "barnSwallow",
    name: "Barn Swallow",
    latin: "Hirundo rustica",
    tier: "uncommon",
    price: 50,
    pronoun: "he",
    seasons: ["spring", "summer"],
    moveLine: "Loops the whole zone in one long, low pass.",
    signature: { id: "zoneLoop", line: "Loops the whole zone in one long, low pass." },
    perchTypes: ["fencePost", "highBranch", "nestBox"],
    presetNames: ["Swoop", "Dart", "Skimmer", "Loop", "Forky", "Glide"],
    wow: "He catches all his food in the air — he even drinks by skimming the pond mid-flight.",
    facts: {
      howBig: "About as long as a pencil, with long forked tail streamers",
      eats: "Flying insects, snapped up on the wing",
      lives: "Open country on every continent except Antarctica — his mud nest sits on barns everywhere",
      doing: "Thriving — the most widespread swallow in the world",
    },
    callCaption: "♪ a fast, cheerful twitter on the wing",
  },
  {
    id: "barnOwl",
    name: "Barn Owl",
    latin: "Tyto alba",
    tier: "uncommon",
    price: 55,
    pronoun: "he",
    seasons: null,
    moveLine: "Flies a silent circuit at dusk. Nothing hears him.",
    signature: { id: "silentCircuit", line: "Flies a silent circuit at dusk. Nothing hears him." },
    perchTypes: ["trunkHollow", "nestBox", "log"],
    presetNames: ["Ghost", "Moon", "Whisper", "Dusk", "Soot", "Silo"],
    wow: "He flies so quietly that mice never hear him coming.",
    facts: {
      howBig: "About as tall as a bowling pin, with a white heart-shaped face",
      eats: "Mice and voles — a family of barn owls eats thousands in a year",
      lives: "Farmland and open country on every continent except Antarctica",
      doing: "Needs friends in some places — but put up a nest box and he moves right in",
    },
    callCaption: "♪ a long, raspy screech — no hoot at all",
  },
  {
    id: "puffin",
    name: "Atlantic Puffin",
    latin: "Fratercula arctica",
    tier: "rare",
    price: 95,
    pronoun: "he",
    seasons: null,
    moveLine: "Waddles, then rockets off the water. Tap him and he shows you his beak full of fish.",
    signature: { id: "waterRocket", line: "Waddles, then rockets off the water." },
    tapResponse: "Shows you his beak full of fish.",
    ownHour: "morning",
    perchTypes: ["pondEdge", "log", "ground"],
    presetNames: ["Puff", "Captain", "Fisher", "Waddles", "Beaky", "Skerry"],
    wow: "He can hold a whole row of little fish crosswise in his beak at once.",
    facts: {
      howBig: "About as tall as a water bottle",
      eats: "Small silver fish, caught by flying underwater on stubby wings",
      lives: "The cold North Atlantic — cliff islands from Maine to Iceland",
      doing: "Needs friends — people brought puffins back to Maine's islands, and it worked",
    },
    callCaption: "♪ a low growl from inside the burrow, like a tiny chainsaw",
  },
  {
    id: "sandhillCrane",
    name: "Sandhill Crane",
    latin: "Antigone canadensis",
    tier: "rare",
    price: 100,
    pronoun: "she",
    seasons: ["autumn"],
    moveLine: "Bugles, and every other bird looks up. Leads the autumn V.",
    signature: { id: "bugle", line: "Bugles, and every other bird looks up." },
    tapResponse: "Answers with a rolling bugle.",
    ownHour: "morning",
    perchTypes: ["reeds", "ground", "pondEdge"],
    presetNames: ["Trumpet", "Sandy", "Stilts", "Rattle", "Prairie", "Echo"],
    wow: "Cranes like her have been bugling across the sky for millions of years — fossils prove it.",
    facts: {
      howBig: "Nearly as tall as you",
      eats: "Grains, roots and small creatures, found while striding through fields",
      lives: "Prairies and wetlands across North America; great rivers on migration",
      doing: "Doing OK — half a million gather on one Nebraska river every spring",
    },
    callCaption: "♪ a rolling, rattling bugle you can hear a mile away",
  },
  {
    id: "paintedBunting",
    name: "Painted Bunting",
    latin: "Passerina ciris",
    tier: "rare",
    price: 110,
    pronoun: "he",
    seasons: ["summer"],
    moveLine: "Preens in the open. Tap him and he turns to show a different colour.",
    signature: { id: "preenShow", line: "Preens in the open." },
    tapResponse: "Turns to show a different colour.",
    ownHour: "midday",
    perchTypes: ["lowBranch", "highBranch", "fencePost"],
    presetNames: ["Rainbow", "Paint", "Palette", "Berry", "Prism", "Doodle"],
    wow: "He looks like he flew through a paint box — red chest, blue head, green back.",
    facts: {
      howBig: "Smaller than your fist",
      eats: "Grass seeds most of the year, insects for his chicks",
      lives: "Summers in brushy thickets of the American south; winters in the tropics",
      doing: "Needs friends — people are planting the tangled bushes he nests in",
    },
    callCaption: "♪ a sweet, jumbly warble from the top of a bush",
  },
  {
    id: "kestrel",
    name: "American Kestrel",
    latin: "Falco sparverius",
    tier: "rare",
    price: 120,
    pronoun: "she",
    seasons: null,
    moveLine: "Hovers dead still, then stoops. Nearby birds scatter when she lands.",
    signature: { id: "hoverStoop", line: "Hovers dead still, then stoops." },
    tapResponse: "Bobs her head twice, sizing you up.",
    ownHour: "dusk",
    perchTypes: ["fencePost", "highBranch"],
    presetNames: ["Skye", "Falca", "Hover", "Windy", "Arrow", "Pippin"],
    wow: "She can hang perfectly still in a moving wind, as if pinned to the sky.",
    facts: {
      howBig: "About as long as a school ruler — the smallest falcon in North America",
      eats: "Grasshoppers, beetles and mice, spotted from high above",
      lives: "Open fields and roadsides across the Americas",
      doing: "Needs friends — nest boxes on farm posts are helping her come back",
    },
    callCaption: "♪ klee-klee-klee-klee!",
  },
  {
    id: "snowyOwl",
    name: "Snowy Owl",
    latin: "Bubo scandiacus",
    tier: "rare",
    price: 125,
    pronoun: "she",
    seasons: ["winter"],
    moveLine: "Sits through the snow without blinking. Hunts in daylight, unlike any other owl here.",
    signature: { id: "snowWatch", line: "Sits through the snow without blinking." },
    tapResponse: "Swivels her head almost all the way around to look at you.",
    ownHour: "midday",
    perchTypes: ["ground", "log", "fencePost"],
    presetNames: ["Boo", "Tundra", "Aurora", "Drift", "Luna", "Glacier"],
    wow: "Her feathers keep her warm at forty degrees below zero — even her toes are feathered.",
    facts: {
      howBig: "About as tall as your arm is long",
      eats: "Lemmings, mostly — in a good year, a family eats thousands",
      lives: "The Arctic tundra; some winters she drifts south to fields and beaches",
      doing: "Very rare — scientists track her flights by satellite to learn how to help",
    },
    callCaption: "♪ a deep, dry hoo — mostly she is silent",
  },
  {
    id: "whoopingCrane",
    name: "Whooping Crane",
    latin: "Grus americana",
    tier: "legendary",
    price: null,
    egg: true,
    eggPrice: 180,
    pronoun: "she",
    seasons: null,
    moveLine: "Dances — a ten-second display that stops the meadow to watch.",
    signature: { id: "craneDance", line: "Dances — leaps, bows and wing-flares." },
    tapResponse: "Bows, and waits for you to bow back.",
    ownHour: "morning",
    setPiece: { id: "dance", seconds: 10 },
    perchTypes: ["reeds", "ground", "pondEdge"],
    presetNames: ["Hope", "Whooper", "Grace", "Journey", "Lily", "North"],
    wow: "She is the tallest bird in North America — and one of the rarest.",
    facts: {
      howBig: "Taller than a kitchen table",
      eats: "Blue crabs, frogs and grains from the marsh",
      lives: "Wetlands — one wild flock flies between Canada and the Texas coast every year",
      doing: "Very rare — once just 15 were left; now there are over 800, and people even taught young cranes the migration route. It's working",
    },
    callCaption: "♪ a loud, clear whoop that carries for miles",
  },
  {
    id: "condor",
    name: "California Condor",
    latin: "Gymnogyps californianus",
    tier: "legendary",
    price: null,
    egg: true,
    eggPrice: 180,
    pronoun: "he",
    seasons: null,
    moveLine: "Opens wings wider than a door and rides a thermal out of frame and back.",
    signature: { id: "thermalRide", line: "Opens wings wider than a door and rides a thermal." },
    tapResponse: "Half-opens those enormous wings to warm them in the sun.",
    ownHour: "midday",
    setPiece: { id: "soar", seconds: 10 },
    perchTypes: ["highBranch", "log", "ground"],
    presetNames: ["Titan", "Canyon", "Sierra", "Glider", "Condorito", "Big Sur"],
    wow: "His wings stretch wider than a door — he can soar for an hour without a single flap.",
    facts: {
      howBig: "Wings nearly three metres tip to tip — the widest in North America",
      eats: "He is nature's clean-up crew, tidying what other animals leave behind",
      lives: "Mountains and big-sky country in California, Arizona and Baja",
      doing: "Very rare — once just 22 were left; now more than 500, and most fly free again",
    },
    callCaption: "♪ mostly silence — just the whoosh of huge wings",
  },
];

export const SPECIES_BY_ID = Object.fromEntries(SPECIES.map((s) => [s.id, s]));

export function tierOf(species) {
  return TIERS[species.tier];
}

/** Species present in a given season ("spring"|"summer"|"autumn"|"winter"). */
export function presentInSeason(species, season) {
  return !species.seasons || species.seasons.includes(season);
}

export function isSeasonal(species) {
  return Array.isArray(species.seasons);
}
