/**
 * The SQL the live step writes to files for a human-approved run. Nothing
 * here executes anything.
 *
 * Inserts only (on conflict (item_id) do nothing): a rerun never overwrites
 * a row, and the checksum afterwards names any row that differs. Rows are
 * carried whole as JSON through jsonb_to_recordset, the way
 * scripts/multiDigit/loadCalcItems.mjs loads the script rows.
 */
import { checksumOf, checksumSql, lineSql, rowMd5Sql } from "../../../src/itemModels/live/liveRows.js";
import { dollar, sqlString } from "./common.mjs";

/** The rows a topic and grade has live in the bank: what a manifest's md5 covers. */
export function liveWhere(topic, grade) {
  return `mode_id = ${sqlString(topic)} and version = 2 and review_status <> 'retired' and tags->>'grade' = ${sqlString(String(grade))}`;
}

// Column, recordset type. The order is the insert's.
const RECORD = [
  ["item_id", "text"],
  ["mode_id", "text"],
  ["item_family", "text"],
  ["subskill", "text"],
  ["structure_type", "text"],
  ["level_min", "int"],
  ["level_max", "int"],
  ["review_status", "text"],
  ["version", "int"],
  ["payload", "jsonb"],
  ["hint", "jsonb"],
  ["blueprint_id", "text"],
  ["difficulty", "text"],
  ["tags", "jsonb"],
  ["item_model_id", "text"],
  ["representation_type", "text"],
  ["source", "jsonb"],
  ["kid_safe", "jsonb"],
];
const RECORD_TYPES = RECORD.map(([c, t]) => `${c} ${t}`).join(", ");
const RECORD_COLS = RECORD.map(([c]) => c).join(", ");

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function recordset(rows) {
  const json = JSON.stringify(rows.map((r) => Object.fromEntries(RECORD.map(([c]) => [c, r[c] ?? null]))));
  return `select * from jsonb_to_recordset(${dollar("c", json)}::jsonb) as x(${RECORD_TYPES})`;
}

/**
 * Split rows into insert statements of at most `chunkKb` each. Returns
 * [{ name, sql, trySql, rows, checksum }]: `sql` inserts and returns how
 * many rows it added; `trySql` is read-only and returns the checksum the
 * chunk's own rows give in Postgres, which must equal `checksum` (proof
 * the SQL carries what this script made, before anything is written).
 */
export function insertChunks(rows, { run, topic, grade, status, reviewedBy = null, chunkKb = 100 }) {
  if (status === "approved" && !UUID.test(String(reviewedBy))) throw new Error(`an approved write needs the reviewer's user id (got ${reviewedBy})`);
  const reviewer = status === "approved" ? `${sqlString(reviewedBy)}::uuid` : "null";
  const reviewedAt = status === "approved" ? "now()" : "null";
  const limit = chunkKb * 1024;
  const groups = [];
  let current = [];
  let size = 0;
  for (const row of rows) {
    if (row.review_status !== status) throw new Error(`${row.item_id}: status ${row.review_status}, run status ${status}`);
    const bytes = Buffer.byteLength(JSON.stringify(row));
    if (current.length && size + bytes > limit) {
      groups.push(current);
      current = [];
      size = 0;
    }
    current.push(row);
    size += bytes;
  }
  if (current.length) groups.push(current);
  const pad = (n) => String(n).padStart(3, "0");
  return groups.map((group, i) => {
    const name = `insert-${pad(i + 1)}`;
    const head = `-- Live step ${run}: ${topic} grade ${grade}, ${name} of ${groups.length} (${group.length} rows, ${status}).
-- Generated by scripts/live/prepare.mjs; do not edit. Insert only: a row that already exists is left
-- as it is. Run in file order, then checksum.sql.
`;
    const sql = `${head}with r as (
  ${recordset(group)}
), ins as (
  insert into public.item_bank (${RECORD_COLS}, reviewed_by, reviewed_at)
  select ${RECORD_COLS}, ${reviewer}, ${reviewedAt}
    from r
  on conflict (item_id) do nothing
  returning 1
)
select (select count(*) from r) as rows_in_file, (select count(*) from ins) as inserted;
`;
    const trySql = `-- Read-only check of ${name}.sql (${run}): the checksum its rows give in Postgres. Expected:
--   rows ${group.length}, checksum ${checksumOf(group)}
with r as (
  ${recordset(group)}
)
select count(*) as rows, md5(string_agg(${lineSql("r")}, E'\\n' order by r.item_id collate "C")) as checksum
  from r;
`;
    return { name, sql, trySql, rows: group.length, checksum: checksumOf(group) };
  });
}

/** Approve a topic and grade's draft blueprint rows (approval lives in the database), deferred rows included: the list was approved whole. */
export function blueprintApprovalSql(ids, { reviewedBy, run }) {
  if (!ids.length) return null;
  if (!UUID.test(String(reviewedBy))) throw new Error(`blueprint approval needs the reviewer's user id (got ${reviewedBy})`);
  return `-- Live step ${run}: approve the topic and grade's ${ids.length} draft blueprint rows (the owner approved the
-- lists; approval lives in the database). Only drafts move; an approved or struck row is left alone.
with u as (
  update public.blueprint_rows
     set status = 'approved', reviewed_by = ${sqlString(reviewedBy)}::uuid, reviewed_at = now()
   where status = 'draft' and id in (${ids.map(sqlString).join(", ")})
  returning 1
)
select count(*) as approved from u;
`;
}

/**
 * The topic's switch row at preview, written only when the topic has no
 * row: the code's default for a v2-only topic is already preview, and the
 * row makes the database's coverage views agree with it. A row that
 * exists is never changed here (a flip is the owner's act).
 */
export function switchSql(topic, { run }) {
  return `-- Live step ${run}: the ${topic} switch row at preview, only if the topic has none yet.
insert into public.item_version_switch (mode_id, live_version, note)
values (${sqlString(topic)}, 'preview', ${sqlString(`live step ${run}`)})
on conflict (mode_id) do nothing
returning mode_id, live_version;
`;
}

/** checksum.sql and rows.sql for a topic and grade, with what they must return. */
export function checkSql(topic, grade, { rows, checksum, run }) {
  const where = liveWhere(topic, grade);
  return {
    checksum: `-- Live step ${run}: the ${topic} grade ${grade} rows live in the bank. Expected:
--   rows ${rows}, checksum ${checksum}
${checksumSql(where)}`,
    rows: `-- Live step ${run}: each live ${topic} grade ${grade} row's md5, to name the rows that differ
-- (compare with expected-rows.json, or save the result as rows.json for readiness.mjs).
${rowMd5Sql(where)}`,
  };
}
