/**
 * The SQL the live step writes to files for a human-approved run. Nothing
 * here executes anything.
 *
 * Inserts only (on conflict (item_id) do nothing): a rerun never overwrites
 * a row, and the checksum afterwards names any row that differs. Rows are
 * carried whole as JSON through jsonb_to_recordset, the way
 * scripts/multiDigit/loadCalcItems.mjs loads the script rows.
 */
import { checksumOf, checksumSql, lineSql, rowMd5Sql } from "../../../src/itemModels/live/liveRows.js";
import { dollar, sqlString } from "./common.mjs";

/** The rows a topic and grade has live in the bank: what a manifest's md5 covers. */
export function liveWhere(topic, grade) {
  return `mode_id = ${sqlString(topic)} and version = 2 and review_status <> 'retired' and tags->>'grade' = ${sqlString(String(grade))}`;
}

// Column, recordset type. The order is the insert's.
const RECORD = [
  ["item_id", "text"],
  ["mode_id", "text"],
  ["item_family", "text"],
  ["subskill", "text"],
  ["structure_type", "text"],
  ["level_min", "int"],
  ["level_max", "int"],
  ["review_status", "text"],
  ["version", "int"],
  ["payload", "jsonb"],
  ["hint", "jsonb"],
  ["blueprint_id", "text"],
  ["difficulty", "text"],
  ["tags", "jsonb"],
  ["item_model_id", "text"],
  ["representation_type", "text"],
  ["source", "jsonb"],
  ["kid_safe", "jsonb"],
];
const RECORD_TYPES = RECORD.map(([c, t]) => `${c} ${t}`).join(", ");
const RECORD_COLS = RECORD.map(([c]) => c).join(", ");

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function recordset(rows) {
  const json = JSON.stringify(rows.map((r) => Object.fromEntries(RECORD.map(([c]) => [c, r[c] ?? null]))));
  return `select * from jsonb_to_recordset(${dollar("c", json)}::jsonb) as x(${RECORD_TYPES})`;
}

/**
 * Split rows into insert statements of at most `chunkKb` each. Returns
 * [{ name, sql, trySql, rows, checksum }]: `sql` inserts and returns how
 * many rows it added; `trySql` is read-only and returns the checksum the
 * chunk's own rows give in Postgres, which must equal `checksum` (proof
 * the SQL carries what this script made, before anything is written).
 */
export function insertChunks(rows, { run, topic, grade, status, reviewedBy = null, chunkKb = 100 }) {
  if (status === "approved" && !UUID.test(String(reviewedBy))) throw new Error(`an approved write needs the reviewer's user id (got ${reviewedBy})`);
  const reviewer = status === "approved" ? `${sqlString(reviewedBy)}::uuid` : "null";
  const reviewedAt = status === "approved" ? "now()" : "null";
  const limit = chunkKb * 1024;
  const groups = [];
  let current = [];
  let size = 0;
  for (const row of rows) {
    if (row.review_status !== status) throw new Error(`${row.item_id}: status ${row.review_status}, run status ${status}`);
    const bytes = Buffer.byteLength(JSON.stringify(row));
    if (current.length && size + bytes > limit) {
      groups.push(current);
      current = [];
      size = 0;
    }
    current.push(row);
    size += bytes;
  }
  if (current.length) groups.push(current);
  const pad = (n) => String(n).padStart(3, "0");
  return groups.map((group, i) => {
    const name = `insert-${pad(i + 1)}`;
    const head = `-- Live step ${run}: ${topic} grade ${grade}, ${name} of ${groups.length} (${group.length} rows, ${status}).
-- Generated by scripts/live/prepare.mjs; do not edit. Insert only: a row that already exists is left
-- as it is. Run in file order, then checksum.sql.
`;
    const sql = `${head}with r as (
  ${recordset(group)}
), ins as (
  insert into public.item_bank (${RECORD_COLS}, reviewed_by, reviewed_at)
  select ${RECORD_COLS}, ${reviewer}, ${reviewedAt}
    from r
  on conflict (item_id) do nothing
  returning 1
)
select (select count(*) from r) as rows_in_file, (select count(*) from ins) as inserted;
`;
    const trySql = `-- Read-only check of ${name}.sql (${run}): the checksum its rows give in Postgres. Expected:
--   rows ${group.length}, checksum ${checksumOf(group)}
with r as (
  ${recordset(group)}
)
select count(*) as rows, md5(string_agg(${lineSql("r")}, E'\\n' order by r.item_id collate "C")) as checksum
  from r;
`;
    return { name, sql, trySql, rows: group.length, checksum: checksumOf(group) };
  });
}

/**
 * An update that fires only on the count it expects, as one statement: the
 * file is safe to run whole (the SQL editor and execute_sql run every
 * statement). Every sub-statement of a WITH sees the same snapshot, so `c`
 * counts the rows before the update. Returns the preview and the update,
 * which reports matched, expected and the rows it changed (0 when matched
 * differs from expected: nothing changes).
 */
export function guardedUpdateSql({ table, where, set, expected, previewAs, updatedAs, returning = "1" }) {
  if (!Number.isInteger(expected) || expected < 0) throw new Error(`a guarded update needs the expected row count (got ${expected})`);
  return `-- 1. Preview (read-only). Expected: ${expected}.
select count(*) as ${previewAs} from ${table}
 where ${where};

-- 2. The update. It changes nothing unless exactly ${expected} rows match, so this file is safe to run whole;
--    check that ${updatedAs} = expected afterwards.
with c as (
  select count(*) as n from ${table}
   where ${where}
), u as (
  update ${table}
     set ${set}
   where ${where}
     and (select n from c) = ${expected}
  returning ${returning}
)
select (select n from c) as matched, ${expected} as expected, count(*) as ${updatedAs} from u;
`;
}

/** The note a live-step blueprint approval leaves on each row it moves (the rollback keys on it). */
export const blueprintStamp = (run) => `approved by live step ${run}`;

/**
 * Approve a topic and grade's draft blueprint rows (approval lives in the
 * database), deferred rows included: the list was approved whole. Each row
 * it moves is stamped with the run in `note`, so blueprintRollbackSql can
 * move exactly those back.
 */
export function blueprintApprovalSql(ids, { reviewedBy, run }) {
  if (!ids.length) return null;
  if (!UUID.test(String(reviewedBy))) throw new Error(`blueprint approval needs the reviewer's user id (got ${reviewedBy})`);
  const stamp = sqlString(blueprintStamp(run));
  return `-- Live step ${run}: approve the topic and grade's ${ids.length} draft blueprint rows (the owner approved the
-- lists; approval lives in the database). Only drafts move; an approved or struck row is left alone. Each row
-- moved carries ${stamp} in its note: rollback/unapprove-blueprints.sql undoes exactly those.
with u as (
  update public.blueprint_rows
     set status = 'approved', reviewed_by = ${sqlString(reviewedBy)}::uuid, reviewed_at = now(),
         note = concat_ws(' | ', nullif(note, ''), ${stamp})
   where status = 'draft' and id in (${ids.map(sqlString).join(", ")})
  returning id
)
select count(*) as approved, array_agg(id order by id) as ids from u;
`;
}

/**
 * Undo blueprintApprovalSql: the rows it stamped go back to draft, with no
 * reviewer, and the stamp leaves the note. Guarded on the count it moved.
 */
export function blueprintRollbackSql(ids, { run, expected = ids.length }) {
  if (!ids.length) return null;
  const stamp = blueprintStamp(run);
  const where = `id in (${ids.map(sqlString).join(", ")})
     and status = 'approved' and position(${sqlString(stamp)} in coalesce(note, '')) > 0`;
  return `-- Undo live step ${run}'s blueprint approval: the rows it approved (stamped ${sqlString(stamp)}) go back to draft.
-- Run only after the run's item rows are back to draft (rollback/unapprove-rows.sql), and only after a go.
-- The expected count, ${expected}, is the export's draft rows: if 01-blueprints.sql approved another number,
-- change it in "(select n from c) = ..." and "... as expected" first.
${guardedUpdateSql({
  table: "public.blueprint_rows",
  where,
  set: `status = 'draft', reviewed_by = null, reviewed_at = null,
         note = nullif(trim(both ' |' from replace(note, ${sqlString(stamp)}, '')), '')`,
  expected,
  previewAs: "would_unapprove",
  updatedAs: "unapproved",
})}`;
}

/**
 * The topic's switch row at preview, written only when the topic has no
 * row: the code's default for a v2-only topic is already preview, and the
 * row makes the database's coverage views agree with it. A row that
 * exists is never changed here (a flip is the owner's act).
 */
export function switchSql(topic, { run }) {
  return `-- Live step ${run}: the ${topic} switch row at preview, only if the topic has none yet.
insert into public.item_version_switch (mode_id, live_version, note)
values (${sqlString(topic)}, 'preview', ${sqlString(`live step ${run}`)})
on conflict (mode_id) do nothing
returning mode_id, live_version;
`;
}

/**
 * checksum.sql and the rows pages for a topic and grade, with what they must
 * return. The rows read pages by `page` (item_bank reads page: CLAUDE.md),
 * one file per page for the rows the run expects, saved as rows-001.json
 * ... for readiness.mjs, which checks the pages against live.json's count.
 * When the checksum shows another count, page by that one instead
 * (exportSql.mjs --for readiness --live <live.json>).
 */
export function checkSql(topic, grade, { rows, checksum, run, page = 1000 }) {
  const where = liveWhere(topic, grade);
  const pages = Math.max(1, Math.ceil(rows / page));
  const pad = (n) => String(n).padStart(3, "0");
  return {
    checksum: `-- Live step ${run}: the ${topic} grade ${grade} rows live in the bank. Expected:
--   rows ${rows}, checksum ${checksum}
${checksumSql(where)}`,
    rowPages: Array.from({ length: pages }, (_, i) => ({
      name: `91-rows-${pad(i + 1)}`,
      sql: `-- Live step ${run}: each live ${topic} grade ${grade} row's md5, page ${i + 1} of ${pages}, to name the rows that
-- differ (compare with expected-rows.json, or save the result as rows-${pad(i + 1)}.json for readiness.mjs, beside
-- the live.json and switch.json that exportSql.mjs --for readiness prints).
${rowMd5Sql(where, { limit: page, offset: i * page })}`,
    })),
  };
}
