import { createQuestionMetadata } from "./itemMetadata";
import { factsForLevel, opsForLevel } from "../facts/factSets.js";
import { factQuestion, formatApplies } from "../facts/factItems.js";

/**
 * Math Facts: the basic facts as their own topic (fact fluency plan B3), so
 * fluency has its own version switch and goes live without waiting on the
 * rework of the four operation topics.
 *
 * Every fact and format is a v2 bank row generated by script from the same
 * modules this file reads (scripts/facts/generateFacts.mjs), so the bank
 * serves this topic. The generator here is only the fallback, and it builds
 * the same questions: no story prose, every answer typed except true or false.
 *
 * Levels are the bank band: addition and subtraction to 5, 10 and 20 at
 * levels 1-6, times tables to 10 x 10 and the 11s and 12s at 7-10.
 */

const SUBSKILLS = ["addFacts", "subFacts", "mulFacts", "divFacts"];
const OP_FOR_SUBSKILL = { addFacts: "add", subFacts: "sub", mulFacts: "mul", divFacts: "div" };

// Plain facts most of the time, stacked now and then; missing numbers mostly,
// true or false a few.
const FORMATS_BY_FAMILY = {
  procedural: ["plain", "plain", "stacked"],
  conceptual: ["missing", "missing", "trueFalse"],
};

const STANDARD_REFS = {
  add: ["K.OA.A.5", "1.OA.C.6", "2.OA.B.2"],
  sub: ["K.OA.A.5", "1.OA.C.6", "2.OA.B.2"],
  mul: ["3.OA.C.7"],
  div: ["3.OA.C.7"],
};

const pick = (list) => list[Math.floor(Math.random() * list.length)];

export default {
  id: "mathFacts",
  label: "Math Facts",
  shortLabel: "Facts",
  description: "Add, subtract, multiply and divide from memory.",
  icon: "Hash",
  glyph: "=",
  op: "+",
  subskills: SUBSKILLS,
  // Band-scoped: addition and subtraction to level 6, times tables from 7.
  subskillLevels: { addFacts: [1, 6], subFacts: [1, 6], mulFacts: [7, 10], divFacts: [7, 10] },
  supportedFormats: [],
  families: ["procedural", "conceptual"],
  // No v1 rows: live at v2 unless its switch row says otherwise (topicVisible).
  v2Only: true,

  generate(level, context = {}) {
    const ops = opsForLevel(level);
    const wanted = OP_FOR_SUBSKILL[context.targetSubskill];
    const op = ops.includes(wanted) ? wanted : pick(ops);
    const itemFamily =
      context.itemFamily === "procedural" || context.itemFamily === "conceptual"
        ? context.itemFamily
        : pick(["procedural", "conceptual"]);

    const facts = factsForLevel(level, op);
    const format = pick(FORMATS_BY_FAMILY[itemFamily].filter((fmt) => facts.some((f) => formatApplies(f, fmt))));
    const fact = pick(facts.filter((f) => formatApplies(f, format)));
    const question = factQuestion(fact, format, { truthy: Math.random() < 0.5 });

    question.level = level;
    question.metadata = createQuestionMetadata({
      modeId: "mathFacts",
      level,
      domain: "OA",
      cluster: op === "add" || op === "sub" ? "Add and subtract within 20" : "Multiply and divide within 100",
      subskill: fact.subskill,
      itemFamily,
      cognitiveDemand: "DOK1",
      representation: "symbolic",
      mathPractices: ["MP7", "MP8"],
      standardRefs: STANDARD_REFS[op],
      misconceptionTags: [],
      blueprintId: fact.rowId,
      structureType: `${op}-${format}`,
    });
    return question;
  },

  // Typed answers need no options; true or false brings its own two.
  generateChoices(answer, question) {
    if (Array.isArray(question?.choices) && question.choices.length >= 2) return question.choices;
    const n = Number(answer);
    const near = [n + 1, n - 1, n + 2, n + 10].filter((x) => x >= 0 && x !== n);
    return [n, ...near.slice(0, 3)].sort(() => Math.random() - 0.5);
  },
};
