export const REVIEW_STATUS = {
  DRAFT: "draft",
  REVIEWED: "reviewed",
  APPROVED: "approved",
  RETIRED: "retired",
};

const APPROVED = REVIEW_STATUS.APPROVED;

// Curated word-problem item bank for application-family items.
// Style guide: see docs/word-problem-authoring-guide.md
//
// Conventions:
// - itemId: <mode>-app-<3-digit-sequence>
// - levelRange covers the engine levels at which an item is appropriate.
// - All currently approved items target levels 7-10 (engine policy: application
//   items unlock from level 7+ outside placeValue, which uses the BUILD type).
// - One unambiguous answer; numbers chosen to discourage guessing or rote recall.

export const APPLICATION_ITEM_BANK = [
  // ---------------- Addition ----------------
  {
    itemId: "addition-app-001",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 7,
      op: "+",
      answer: 16,
      display: { promptText: "Mina has 9 shells and finds 7 more. How many shells does she have now?" },
    },
  },
  {
    itemId: "addition-app-002",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: 6,
      op: "+",
      answer: 14,
      display: { promptText: "There are 8 ducks at the pond. 6 more ducks arrive. How many ducks are at the pond now?" },
    },
  },
  {
    itemId: "addition-app-003",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "partPartWhole",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: 9,
      op: "+",
      answer: 16,
      display: { promptText: "A class has 7 red balloons and 9 blue balloons. How many balloons in all?" },
    },
  },
  {
    itemId: "addition-app-004",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 28,
      b: 16,
      op: "+",
      answer: 44,
      display: { promptText: "A bookshelf has 28 books. The librarian adds 16 more. How many books are on the shelf now?" },
    },
  },
  {
    itemId: "addition-app-005",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 18,
      b: 14,
      op: "+",
      answer: 32,
      display: { promptText: "A class plants 18 flowers on Monday and 14 on Tuesday. How many flowers were planted in all?" },
    },
  },
  {
    itemId: "addition-app-006",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 23,
      b: 17,
      op: "+",
      answer: 40,
      display: { promptText: "A bakery sells 23 muffins in the morning and 17 in the afternoon. How many muffins were sold today?" },
    },
  },
  {
    itemId: "addition-app-007",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "joinResultUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 35,
      b: 28,
      op: "+",
      answer: 63,
      display: { promptText: "A school has 35 first-graders and 28 second-graders going on a trip. How many students go on the trip?" },
    },
  },
  {
    itemId: "addition-app-008",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 46,
      b: 27,
      op: "+",
      answer: 73,
      display: { promptText: "A team scored 46 points in the first half and 27 in the second half. How many points did they score in all?" },
    },
  },
  {
    itemId: "addition-app-009",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 26,
      b: null,
      op: "+",
      answer: 13,
      display: { promptText: "Luca has 26 cards. He gets some more and now has 39 cards. How many cards did he get?" },
    },
  },
  {
    itemId: "addition-app-010",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 12,
      b: null,
      op: "+",
      answer: 8,
      display: { promptText: "Sam has 12 stickers. After trading, Sam has 20 stickers. How many stickers did Sam get?" },
    },
  },
  {
    itemId: "addition-app-011",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "compareDifferenceUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 18,
      b: null,
      op: "+",
      answer: 14,
      display: { promptText: "Ava has 18 marbles. She needs 32 marbles in total. How many more marbles does she need?" },
    },
  },
  {
    itemId: "addition-app-012",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 30,
      b: null,
      op: "+",
      answer: 25,
      display: { promptText: "A bus had 30 riders. After the next stop it has 55 riders. How many riders got on at the stop?" },
    },
  },
  {
    itemId: "addition-app-013",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 19,
      b: 8,
      op: "+",
      answer: 27,
      display: { promptText: "A pond has 19 frogs. 8 more arrive. How many frogs are at the pond now?" },
    },
  },
  {
    itemId: "addition-app-014",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 24,
      b: 19,
      op: "+",
      answer: 43,
      display: { promptText: "A library lent 24 fiction books and 19 non-fiction books. How many books were lent?" },
    },
  },
  {
    itemId: "addition-app-015",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 22,
      b: null,
      op: "+",
      answer: 16,
      display: { promptText: "A jar held 22 candies. After more were added, the jar held 38. How many candies were added?" },
    },
  },

  // ---------------- Addition: Phase 1 K-1 + 2-3 backfill ----------------
  // makeTen / K-1 (levels 1-3): friendly sums to ten using small concrete sets.
  {
    itemId: "addition-app-016",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: 3,
      op: "+",
      answer: 10,
      display: { promptText: "There are 7 leaves on a branch. 3 more leaves fall onto it. How many leaves are on the branch now?" },
    },
  },
  {
    itemId: "addition-app-017",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: 4,
      op: "+",
      answer: 10,
      display: { promptText: "Kai sees 6 fish in a tank. 4 more fish swim in. How many fish are in the tank?" },
    },
  },
  {
    itemId: "addition-app-018",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "partPartWhole",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 5,
      b: 5,
      op: "+",
      answer: 10,
      display: { promptText: "Rosa has 5 red blocks and 5 blue blocks. How many blocks does Rosa have in all?" },
    },
  },
  {
    itemId: "addition-app-019",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: 2,
      op: "+",
      answer: 10,
      display: { promptText: "There are 8 cars in the lot. 2 more cars drive in. How many cars are in the lot?" },
    },
  },

  // makeTen / 2-3 (levels 4-6): bridging through ten with sums 11-15.
  {
    itemId: "addition-app-020",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 6,
      op: "+",
      answer: 15,
      display: { promptText: "Hugo bakes 9 cookies in the morning and 6 more in the afternoon. How many cookies did he bake?" },
    },
  },
  {
    itemId: "addition-app-021",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: 7,
      op: "+",
      answer: 15,
      display: { promptText: "Pia collects 8 stickers on Monday and 7 stickers on Tuesday. How many stickers does Pia have?" },
    },
  },
  {
    itemId: "addition-app-022",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "partPartWhole",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: 8,
      op: "+",
      answer: 15,
      display: { promptText: "A book has 7 pages with pictures and 8 pages with words. How many pages are in the book?" },
    },
  },
  {
    itemId: "addition-app-023",
    modeId: "addition",
    itemFamily: "application",
    subskill: "makeTen",
    structureType: "joinResultUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 4,
      op: "+",
      answer: 13,
      display: { promptText: "There are 9 birds in a tree. 4 more birds land in the tree. How many birds are in the tree?" },
    },
  },

  // composeDecompose / K-1 (levels 1-3): two-part wholes within 10.
  {
    itemId: "addition-app-024",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 4,
      b: 3,
      op: "+",
      answer: 7,
      display: { promptText: "Eli has 4 red pencils and 3 green pencils. How many pencils does Eli have?" },
    },
  },
  {
    itemId: "addition-app-025",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: 3,
      op: "+",
      answer: 9,
      display: { promptText: "A basket has 6 oranges and 3 lemons. How many fruits are in the basket?" },
    },
  },
  {
    itemId: "addition-app-026",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 2,
      b: 5,
      op: "+",
      answer: 7,
      display: { promptText: "A bin has 2 small balls and 5 big balls. How many balls are in the bin?" },
    },
  },
  {
    itemId: "addition-app-027",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 4,
      b: 4,
      op: "+",
      answer: 8,
      display: { promptText: "A line has 4 boys and 4 girls. How many children are in the line?" },
    },
  },

  // composeDecompose / 2-3 (levels 4-6): wholes within 20.
  {
    itemId: "addition-app-028",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 12,
      b: 5,
      op: "+",
      answer: 17,
      display: { promptText: "A box has 12 sharp pencils and 5 dull pencils. How many pencils are in the box?" },
    },
  },
  {
    itemId: "addition-app-029",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 8,
      op: "+",
      answer: 17,
      display: { promptText: "A deck has 9 number cards and 8 picture cards. How many cards are in the deck?" },
    },
  },
  {
    itemId: "addition-app-030",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 13,
      b: 6,
      op: "+",
      answer: 19,
      display: { promptText: "An art bin has 13 thin markers and 6 thick markers. How many markers are in the bin?" },
    },
  },
  {
    itemId: "addition-app-031",
    modeId: "addition",
    itemFamily: "application",
    subskill: "composeDecompose",
    structureType: "partPartWhole",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 11,
      b: 7,
      op: "+",
      answer: 18,
      display: { promptText: "A shelf holds 11 small toys and 7 big toys. How many toys are on the shelf?" },
    },
  },

  // unknownAddend / K-1 (levels 1-3): missing addend to make a total <= 10.
  {
    itemId: "addition-app-032",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: null,
      op: "+",
      answer: 4,
      display: { promptText: "A pond has 6 frogs. More frogs hop in. Now there are 10 frogs. How many frogs hopped in?" },
    },
  },
  {
    itemId: "addition-app-033",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 3,
      b: null,
      op: "+",
      answer: 5,
      display: { promptText: "Tia has 3 cookies. Mom gives her some more. Now Tia has 8 cookies. How many did Mom give her?" },
    },
  },
  {
    itemId: "addition-app-034",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "compareDifferenceUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 5,
      b: null,
      op: "+",
      answer: 4,
      display: { promptText: "Ben has 5 toy cars. He needs 9 toy cars to fill his case. How many more cars does he need?" },
    },
  },
  {
    itemId: "addition-app-035",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [1, 3],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: null,
      op: "+",
      answer: 3,
      display: { promptText: "A nest has 7 eggs. A bird lays more eggs. Now there are 10 eggs. How many new eggs were laid?" },
    },
  },

  // unknownAddend / 2-3 (levels 4-6): missing addend within 20.
  {
    itemId: "addition-app-036",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: null,
      op: "+",
      answer: 7,
      display: { promptText: "A plate had 8 cookies. Dad baked more. Now there are 15 cookies on the plate. How many did Dad bake?" },
    },
  },
  {
    itemId: "addition-app-037",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "compareDifferenceUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 12,
      b: null,
      op: "+",
      answer: 8,
      display: { promptText: "Jada has 12 stickers. She wants 20 stickers in her book. How many more stickers does she need?" },
    },
  },
  {
    itemId: "addition-app-038",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "joinChangeUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: null,
      op: "+",
      answer: 8,
      display: { promptText: "Owen had 6 seashells. He found more on the beach. Now he has 14 seashells. How many did he find?" },
    },
  },
  {
    itemId: "addition-app-039",
    modeId: "addition",
    itemFamily: "application",
    subskill: "unknownAddend",
    structureType: "compareDifferenceUnknown",
    levelRange: [4, 6],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: null,
      op: "+",
      answer: 8,
      display: { promptText: "A box has 9 crayons. A full box holds 17 crayons. How many more crayons would fill the box?" },
    },
  },

  // ---------------- Subtraction ----------------
  {
    itemId: "subtraction-app-001",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "differenceAsDistance",
    structureType: "compareDifferenceUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 43,
      b: 28,
      op: "−",
      answer: 15,
      display: { promptText: "Nia read 43 pages this week and 28 pages last week. How many more pages did she read this week?" },
    },
  },
  {
    itemId: "subtraction-app-002",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "differenceAsDistance",
    structureType: "compareDifferenceUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 35,
      b: 18,
      op: "−",
      answer: 17,
      display: { promptText: "Theo collected 35 acorns and Maya collected 18 acorns. How many more did Theo collect?" },
    },
  },
  {
    itemId: "subtraction-app-003",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "differenceAsDistance",
    structureType: "compareDifferenceUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 70,
      b: 46,
      op: "−",
      answer: 24,
      display: { promptText: "A movie sold 70 tickets on Friday and 46 tickets on Thursday. How many more tickets sold on Friday?" },
    },
  },
  {
    itemId: "subtraction-app-004",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "decomposeToSubtract",
    structureType: "separateResultUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 52,
      b: 19,
      op: "−",
      answer: 33,
      display: { promptText: "There are 52 markers in a box. 19 are used in art class. How many markers are left?" },
    },
  },
  {
    itemId: "subtraction-app-005",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "decomposeToSubtract",
    structureType: "separateResultUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 41,
      b: 23,
      op: "−",
      answer: 18,
      display: { promptText: "A bag had 41 grapes. The family ate 23 grapes. How many grapes are left in the bag?" },
    },
  },
  {
    itemId: "subtraction-app-006",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "decomposeToSubtract",
    structureType: "separateResultUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 84,
      b: 39,
      op: "−",
      answer: 45,
      display: { promptText: "A jar holds 84 buttons. 39 are taken out for a craft. How many buttons remain in the jar?" },
    },
  },
  {
    itemId: "subtraction-app-007",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "unknownSubtrahend",
    structureType: "separateChangeUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 61,
      b: null,
      op: "−",
      answer: 24,
      display: { promptText: "A shelf held 61 books. After some were borrowed, 37 remained. How many books were borrowed?" },
    },
  },
  {
    itemId: "subtraction-app-008",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "unknownSubtrahend",
    structureType: "separateChangeUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 30,
      b: null,
      op: "−",
      answer: 12,
      display: { promptText: "Sam started with 30 cookies. After sharing, 18 are left. How many cookies did Sam share?" },
    },
  },
  {
    itemId: "subtraction-app-009",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "unknownSubtrahend",
    structureType: "separateChangeUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 95,
      b: null,
      op: "−",
      answer: 47,
      display: { promptText: "A pond had 95 lily pads. After a storm, 48 lily pads remain. How many lily pads were lost?" },
    },
  },
  {
    itemId: "subtraction-app-010",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "differenceAsDistance",
    structureType: "compareDifferenceUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 88,
      b: 53,
      op: "−",
      answer: 35,
      display: { promptText: "Class A planted 88 seeds and Class B planted 53 seeds. How many more did Class A plant?" },
    },
  },
  {
    itemId: "subtraction-app-011",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "decomposeToSubtract",
    structureType: "separateResultUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 60,
      b: 24,
      op: "−",
      answer: 36,
      display: { promptText: "A bowl has 60 cherries. The family eats 24. How many cherries are left in the bowl?" },
    },
  },
  {
    itemId: "subtraction-app-012",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "unknownSubtrahend",
    structureType: "separateChangeUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 50,
      b: null,
      op: "−",
      answer: 18,
      display: { promptText: "A box held 50 paper clips. After some were used, 32 remained. How many were used?" },
    },
  },
  {
    itemId: "subtraction-app-013",
    modeId: "subtraction",
    itemFamily: "application",
    subskill: "differenceAsDistance",
    structureType: "compareDifferenceUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 27,
      b: 19,
      op: "−",
      answer: 8,
      display: { promptText: "Mia jumped rope 27 times and Eli jumped 19 times. How many more jumps did Mia do?" },
    },
  },

  // ---------------- Multiplication ----------------
  {
    itemId: "multiplication-app-001",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "equalGroups",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: 4,
      op: "×",
      answer: 24,
      display: { promptText: "There are 6 tables with 4 cups on each table. How many cups are there in all?" },
    },
  },
  {
    itemId: "multiplication-app-002",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "equalGroups",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 5,
      b: 6,
      op: "×",
      answer: 30,
      display: { promptText: "5 baskets each hold 6 apples. How many apples are there in all?" },
    },
  },
  {
    itemId: "multiplication-app-003",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "equalGroups",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 4,
      op: "×",
      answer: 36,
      display: { promptText: "A pack has 9 stickers. There are 4 packs. How many stickers in total?" },
    },
  },
  {
    itemId: "multiplication-app-004",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "arrayReasoning",
    structureType: "arrayTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: 5,
      op: "×",
      answer: 35,
      display: { promptText: "A garden has 7 rows of plants with 5 plants in each row. How many plants are there?" },
    },
  },
  {
    itemId: "multiplication-app-005",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "arrayReasoning",
    structureType: "arrayTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: 8,
      op: "×",
      answer: 48,
      display: { promptText: "A parking lot has 6 rows with 8 cars in each row. How many cars are parked in all?" },
    },
  },
  {
    itemId: "multiplication-app-006",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "arrayReasoning",
    structureType: "arrayTotalUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 6,
      op: "×",
      answer: 54,
      display: { promptText: "A theater seats people in 9 rows of 6 seats. How many seats are in the theater?" },
    },
  },
  {
    itemId: "multiplication-app-007",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "factFluency",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: 7,
      op: "×",
      answer: 56,
      display: { promptText: "Each box holds 8 crayons. If there are 7 boxes, how many crayons are there?" },
    },
  },
  {
    itemId: "multiplication-app-008",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "factFluency",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: 7,
      op: "×",
      answer: 49,
      display: { promptText: "A flag has 7 stripes. There are 7 flags. How many stripes in all?" },
    },
  },
  {
    itemId: "multiplication-app-009",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "factFluency",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 9,
      b: 8,
      op: "×",
      answer: 72,
      display: { promptText: "A tray holds 9 muffins. The bakery makes 8 trays. How many muffins are made?" },
    },
  },
  {
    itemId: "multiplication-app-010",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "equalGroups",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 7,
      b: 4,
      op: "×",
      answer: 28,
      display: { promptText: "A team has 7 players. Each player has 4 cards. How many cards do they have in all?" },
    },
  },
  {
    itemId: "multiplication-app-011",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "arrayReasoning",
    structureType: "arrayTotalUnknown",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 5,
      b: 9,
      op: "×",
      answer: 45,
      display: { promptText: "A wall has 5 rows of bricks with 9 bricks in each row. How many bricks make up the wall?" },
    },
  },
  {
    itemId: "multiplication-app-012",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "factFluency",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 6,
      b: 9,
      op: "×",
      answer: 54,
      display: { promptText: "A class has 6 small groups with 9 students each. How many students in all?" },
    },
  },
  {
    itemId: "multiplication-app-013",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "equalGroups",
    structureType: "equalGroupsTotalUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: 5,
      op: "×",
      answer: 40,
      display: { promptText: "A farmer fills 8 crates with 5 melons each. How many melons did the farmer pack?" },
    },
  },
  {
    itemId: "multiplication-app-014",
    modeId: "multiplication",
    itemFamily: "application",
    subskill: "arrayReasoning",
    structureType: "arrayTotalUnknown",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 8,
      b: 6,
      op: "×",
      answer: 48,
      display: { promptText: "A chess board section is 8 squares by 6 squares. How many squares are there?" },
    },
  },

  // ---------------- Division ----------------
  {
    itemId: "division-app-001",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 36,
      b: 6,
      op: "÷",
      answer: 6,
      display: { promptText: "36 apples are shared equally among 6 baskets. How many apples go in each basket?" },
    },
  },
  {
    itemId: "division-app-002",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 24,
      b: 4,
      op: "÷",
      answer: 6,
      display: { promptText: "24 pencils are split equally into 4 groups. How many pencils are in each group?" },
    },
  },
  {
    itemId: "division-app-003",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 45,
      b: 5,
      op: "÷",
      answer: 9,
      display: { promptText: "A teacher hands out 45 markers equally to 5 tables. How many markers does each table get?" },
    },
  },
  {
    itemId: "division-app-004",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 56,
      b: 8,
      op: "÷",
      answer: 7,
      display: { promptText: "56 stickers are packed equally into 8 packets. How many stickers are in each packet?" },
    },
  },
  {
    itemId: "division-app-005",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 42,
      b: 7,
      op: "÷",
      answer: 6,
      display: { promptText: "42 grapes are placed equally into 7 small bowls. How many grapes are in each bowl?" },
    },
  },
  {
    itemId: "division-app-006",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 81,
      b: 9,
      op: "÷",
      answer: 9,
      display: { promptText: "81 chairs are arranged in 9 equal rows. How many chairs are in each row?" },
    },
  },
  {
    itemId: "division-app-007",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 63,
      b: 9,
      op: "÷",
      answer: 7,
      display: { promptText: "A team has 63 cones to share equally among 9 practice groups. How many cones does each group get?" },
    },
  },
  {
    itemId: "division-app-008",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 48,
      b: 6,
      op: "÷",
      answer: 8,
      display: { promptText: "48 cookies are packed 6 per box. How many boxes are filled?" },
    },
  },
  {
    itemId: "division-app-009",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 72,
      b: 8,
      op: "÷",
      answer: 9,
      display: { promptText: "A baker uses 72 eggs, 8 eggs per batch. How many batches did the baker make?" },
    },
  },
  {
    itemId: "division-app-010",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 30,
      b: 5,
      op: "÷",
      answer: 6,
      display: { promptText: "30 stickers are shared equally among 5 friends. How many stickers does each friend get?" },
    },
  },
  {
    itemId: "division-app-011",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 64,
      b: 8,
      op: "÷",
      answer: 8,
      display: { promptText: "64 beads are placed equally on 8 strings. How many beads are on each string?" },
    },
  },
  {
    itemId: "division-app-012",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 35,
      b: 5,
      op: "÷",
      answer: 7,
      display: { promptText: "35 oranges are packed in bags of 5. How many bags did the store fill?" },
    },
  },
  {
    itemId: "division-app-013",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 54,
      b: 6,
      op: "÷",
      answer: 9,
      display: { promptText: "A coach splits 54 cones equally among 6 stations. How many cones go to each station?" },
    },
  },
  {
    itemId: "division-app-014",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 28,
      b: 4,
      op: "÷",
      answer: 7,
      display: { promptText: "28 pears are placed equally into 4 baskets. How many pears go in each basket?" },
    },
  },

  // ---------------- Comparing ----------------
  {
    itemId: "comparing-app-001",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 246,
      b: 264,
      op: "?",
      answer: "<",
      display: { promptText: "Lane A scored 246 points and Lane B scored 264 points. Which symbol compares Lane A to Lane B?" },
    },
  },
  {
    itemId: "comparing-app-002",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 178,
      b: 187,
      op: "?",
      answer: "<",
      display: { promptText: "A class read 178 books and another class read 187 books. Which symbol compares 178 to 187?" },
    },
  },
  {
    itemId: "comparing-app-003",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 510,
      b: 499,
      op: "?",
      answer: ">",
      display: { promptText: "A library counted 510 books on one shelf and 499 on another. Which symbol compares 510 to 499?" },
    },
  },
  {
    itemId: "comparing-app-004",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 805,
      b: 850,
      op: "?",
      answer: "<",
      display: { promptText: "A stadium seats 805 fans and a theater seats 850 fans. Which symbol compares 805 to 850?" },
    },
  },
  {
    itemId: "comparing-app-005",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 380,
      b: 380,
      op: "?",
      answer: "=",
      display: { promptText: "Two classes each solved 380 puzzles this month. Which symbol compares the totals?" },
    },
  },
  {
    itemId: "comparing-app-006",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 612,
      b: 612,
      op: "?",
      answer: "=",
      display: { promptText: "Town A and Town B each have 612 students. Which symbol compares the two amounts?" },
    },
  },
  {
    itemId: "comparing-app-007",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 84,
      b: 79,
      op: "?",
      answer: ">",
      display: { promptText: "A class read 84 books and another class read 79 books. Which symbol compares 84 to 79?" },
    },
  },
  {
    itemId: "comparing-app-008",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 999,
      b: 1001,
      op: "?",
      answer: "<",
      display: { promptText: "A counter shows 999 in one window and 1001 in another. Which symbol compares 999 to 1001?" },
    },
  },
  {
    itemId: "comparing-app-009",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 145,
      b: 145,
      op: "?",
      answer: "=",
      display: { promptText: "Two food drives each collected 145 cans. Which symbol compares the two totals?" },
    },
  },
  {
    itemId: "comparing-app-010",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 432,
      b: 423,
      op: "?",
      answer: ">",
      display: { promptText: "A movie sold 432 tickets and a play sold 423. Which symbol compares 432 to 423?" },
    },
  },
  {
    itemId: "comparing-app-011",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 250,
      b: 205,
      op: "?",
      answer: ">",
      display: { promptText: "A pool has 250 swim laps logged and another has 205. Which symbol compares 250 to 205?" },
    },
  },
  {
    itemId: "comparing-app-012",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 720,
      b: 720,
      op: "?",
      answer: "=",
      display: { promptText: "Two schools each enrolled 720 students. Which symbol compares the two enrollments?" },
    },
  },
  {
    itemId: "comparing-app-013",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 304,
      b: 340,
      op: "?",
      answer: "<",
      display: { promptText: "A garden has 304 tulips and 340 daisies. Which symbol compares 304 to 340?" },
    },
  },

  // ---------------- Counting ----------------
  {
    itemId: "counting-app-001",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 14,
      b: null,
      op: "count",
      answer: 14,
      display: { promptText: "There are 14 toy cars lined up on a shelf. How many toy cars are there?" },
    },
  },
  {
    itemId: "counting-app-002",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 20,
      b: null,
      op: "count",
      answer: 20,
      display: { promptText: "A box has 20 crayons inside. How many crayons are in the box?" },
    },
  },
  {
    itemId: "counting-app-003",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 27,
      b: null,
      op: "count",
      answer: 27,
      display: { promptText: "A jar has 27 marbles. Count to find how many marbles are in the jar." },
    },
  },
  {
    itemId: "counting-app-004",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 42,
      b: null,
      op: "count",
      answer: 42,
      display: { promptText: "A garden has 42 tulips. How many tulips are in the garden?" },
    },
  },
  {
    itemId: "counting-app-005",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 35,
      b: null,
      op: "count",
      answer: 35,
      display: { promptText: "A basket holds 35 oranges. How many oranges are in the basket?" },
    },
  },
  {
    itemId: "counting-app-006",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 50,
      b: null,
      op: "count",
      answer: 50,
      display: { promptText: "A class collected 50 cans for recycling. How many cans were collected?" },
    },
  },
  {
    itemId: "counting-app-007",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 18,
      b: null,
      op: "count",
      answer: 18,
      display: { promptText: "A pencil case has 18 pencils. How many pencils are in the case?" },
    },
  },
  {
    itemId: "counting-app-008",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 31,
      b: null,
      op: "count",
      answer: 31,
      display: { promptText: "A row has 31 chairs set up for a play. How many chairs are in the row?" },
    },
  },
  {
    itemId: "counting-app-009",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 38,
      b: null,
      op: "count",
      answer: 38,
      display: { promptText: "A jar holds 38 cookies. How many cookies are in the jar?" },
    },
  },
  {
    itemId: "counting-app-010",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 24,
      b: null,
      op: "count",
      answer: 24,
      display: { promptText: "A drawer has 24 spoons. How many spoons are in the drawer?" },
    },
  },
  {
    itemId: "counting-app-011",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 47,
      b: null,
      op: "count",
      answer: 47,
      display: { promptText: "A wall has 47 photos hung up. How many photos are on the wall?" },
    },
  },
  {
    itemId: "counting-app-012",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 60,
      b: null,
      op: "count",
      answer: 60,
      display: { promptText: "A box of building blocks has 60 pieces. How many pieces are in the box?" },
    },
  },
  {
    itemId: "counting-app-013",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 16,
      b: null,
      op: "count",
      answer: 16,
      display: { promptText: "A garden has 16 sunflowers. How many sunflowers are in the garden?" },
    },
  },

  // ---------------- Skip Counting ----------------
  {
    itemId: "skipcounting-app-001",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 21,
      display: {
        sequence: [12, 15, 18],
        step: 3,
        promptText: "A student counts by 3s: 12, 15, 18. What number comes next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-002",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 24,
      display: {
        sequence: [6, 12, 18],
        step: 6,
        promptText: "A clock chime rings every 6 minutes: 6, 12, 18. When does it ring next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-003",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 44,
      display: {
        sequence: [32, 36, 40],
        step: 4,
        promptText: "A pattern increases by 4: 32, 36, 40. What comes next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-004",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 80,
      display: {
        sequence: [50, 60, 70],
        step: 10,
        promptText: "A jar fills 10 marbles at a time: 50, 60, 70. How many marbles next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-005",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 60,
      display: {
        sequence: [45, 50, 55],
        step: 5,
        promptText: "A scoreboard goes up by 5 points: 45, 50, 55. What score is next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-006",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 90,
      display: {
        sequence: [75, 80, 85],
        step: 5,
        promptText: "A class earns 5 stars per chapter: 75, 80, 85. How many stars after one more chapter?",
      },
    },
  },
  {
    itemId: "skipcounting-app-007",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 28,
      display: {
        sequence: [16, 20, 24],
        step: 4,
        promptText: "A timer beeps every 4 seconds: 16, 20, 24. When does it beep next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-008",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 30,
      display: {
        sequence: [18, 22, 26],
        step: 4,
        promptText: "A line of beads grows by the same amount each step: 18, 22, 26. What comes next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-009",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 30,
      display: {
        sequence: [12, 18, 24],
        step: 6,
        promptText: "A team adds 6 points each round: 12, 18, 24. How many points after one more round?",
      },
    },
  },
  {
    itemId: "skipcounting-app-010",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 14,
      display: {
        sequence: [2, 6, 10],
        step: 4,
        promptText: "A toy car gains 4 pegs each step: 2, 6, 10. How many pegs next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-011",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 50,
      display: {
        sequence: [20, 30, 40],
        step: 10,
        promptText: "A reader logs minutes growing by the same amount: 20, 30, 40. What comes next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-012",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 35,
      display: {
        sequence: [14, 21, 28],
        step: 7,
        promptText: "A pattern grows by 7 each step: 14, 21, 28. What comes next?",
      },
    },
  },
  {
    itemId: "skipcounting-app-013",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: null,
      b: null,
      op: "skip",
      answer: 36,
      display: {
        sequence: [9, 18, 27],
        step: 9,
        promptText: "A counter goes up by 9 each step: 9, 18, 27. What comes next?",
      },
    },
  },

  // ---------------- Place Value ----------------
  {
    itemId: "placevalue-app-001",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 64,
      b: null,
      op: "place",
      answer: 64,
      display: {
        type: "build",
        number: 64,
        tens: 6,
        ones: 4,
        promptText: "A class builds a number with 6 tens and 4 ones. What number did they build?",
      },
    },
  },
  {
    itemId: "placevalue-app-002",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 128,
      b: null,
      op: "place",
      answer: 128,
      display: {
        type: "build",
        number: 128,
        tens: 12,
        ones: 8,
        promptText: "A puzzle card shows 12 tens and 8 ones. What number is shown?",
      },
    },
  },
  {
    itemId: "placevalue-app-003",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 305,
      b: null,
      op: "place",
      answer: 305,
      display: {
        type: "build",
        number: 305,
        tens: 30,
        ones: 5,
        promptText: "A team records 30 tens and 5 ones. What number do those blocks make?",
      },
    },
  },
  {
    itemId: "placevalue-app-004",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 92,
      b: null,
      op: "place",
      answer: 92,
      display: {
        type: "build",
        number: 92,
        tens: 9,
        ones: 2,
        promptText: "A storage bin holds 9 tens of beads and 2 extra beads. How many beads in all?" ,
      },
    },
  },
  {
    itemId: "placevalue-app-005",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 240,
      b: null,
      op: "place",
      answer: 240,
      display: {
        type: "build",
        number: 240,
        tens: 24,
        ones: 0,
        promptText: "A stack has 24 tens and 0 ones. What number does the stack show?",
      },
    },
  },
  {
    itemId: "placevalue-app-006",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 47,
      b: null,
      op: "place",
      answer: 47,
      display: {
        type: "build",
        number: 47,
        tens: 4,
        ones: 7,
        promptText: "A box has 4 tens of crayons and 7 extra crayons. How many crayons are in the box?",
      },
    },
  },
  {
    itemId: "placevalue-app-007",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 156,
      b: null,
      op: "place",
      answer: 156,
      display: {
        type: "build",
        number: 156,
        tens: 15,
        ones: 6,
        promptText: "A model uses 15 tens of blocks and 6 ones. What number do the blocks show?",
      },
    },
  },
  {
    itemId: "placevalue-app-008",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 503,
      b: null,
      op: "place",
      answer: 503,
      display: {
        type: "build",
        number: 503,
        tens: 50,
        ones: 3,
        promptText: "A counter shows 50 tens and 3 ones. What number is on the counter?",
      },
    },
  },
  {
    itemId: "placevalue-app-009",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 80,
      b: null,
      op: "place",
      answer: 80,
      display: {
        type: "build",
        number: 80,
        tens: 8,
        ones: 0,
        promptText: "A pencil case organizes pencils as 8 tens and 0 ones. How many pencils in all?",
      },
    },
  },
  {
    itemId: "placevalue-app-010",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [8, 10],
    reviewStatus: APPROVED,
    question: {
      a: 213,
      b: null,
      op: "place",
      answer: 213,
      display: {
        type: "build",
        number: 213,
        tens: 21,
        ones: 3,
        promptText: "A garden tracks 21 tens of seeds and 3 ones. How many seeds were tracked?",
      },
    },
  },
  {
    itemId: "placevalue-app-011",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9, 10],
    reviewStatus: APPROVED,
    question: {
      a: 408,
      b: null,
      op: "place",
      answer: 408,
      display: {
        type: "build",
        number: 408,
        tens: 40,
        ones: 8,
        promptText: "A scoreboard reads 40 tens and 8 ones. What number does the scoreboard show?",
      },
    },
  },
  {
    itemId: "placevalue-app-012",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7, 10],
    reviewStatus: APPROVED,
    question: {
      a: 75,
      b: null,
      op: "place",
      answer: 75,
      display: {
        type: "build",
        number: 75,
        tens: 7,
        ones: 5,
        promptText: "A library bin shows 7 tens of cards and 5 ones. How many cards are in the bin?",
      },
    },
  },
];
