// Aggregator for the item bank. Item data lives in the per-mode files under
// ./items/ (split out of the former monolith in Phase 0.4). REVIEW_STATUS is
// re-exported for back-compat with existing importers.
//
// Auto-generated by scripts/lib/itemBankFiles.js — do not hand-edit.

export { REVIEW_STATUS } from "./reviewStatus.js";

import { ITEMS as additionItems } from "./items/addition.js";
import { ITEMS as comparingItems } from "./items/comparing.js";
import { ITEMS as countingItems } from "./items/counting.js";
import { ITEMS as divisionItems } from "./items/division.js";
import { ITEMS as multiplicationItems } from "./items/multiplication.js";
import { ITEMS as numberBondsItems } from "./items/numberBonds.js";
import { ITEMS as placeValueItems } from "./items/placeValue.js";
import { ITEMS as placeValueDiscsItems } from "./items/placeValueDiscs.js";
import { ITEMS as skipCountingItems } from "./items/skipCounting.js";
import { ITEMS as subtractionItems } from "./items/subtraction.js";

export const APPLICATION_ITEM_BANK = [
  ...additionItems,
  ...comparingItems,
  ...countingItems,
  ...divisionItems,
  ...multiplicationItems,
  ...numberBondsItems,
  ...placeValueItems,
  ...placeValueDiscsItems,
  ...skipCountingItems,
  ...subtractionItems,
];
