import XCTest
@testable import KidMath

/// P0 exit criterion: the Swift bridge generates and scores questions through
/// JavaScriptCore identically to Node, where the engine's 354-test suite runs.
final class EngineBridgeTests: XCTestCase {

    private var bridge: EngineBridge!

    override func setUpWithError() throws {
        bridge = try EngineBridge()
    }

    // MARK: - Bundle loads and exposes the API

    func testEngineLoadsAndReportsModes() throws {
        XCTAssertEqual(bridge.version, 1)
        let modes = try bridge.modes()
        XCTAssertGreaterThanOrEqual(modes.count, 20, "expected the full mode list, got \(modes)")
        XCTAssertTrue(modes.contains("addition"))
    }

    // MARK: - Every mode generates and self-scores

    /// A submittable value for a question, the way the UI would submit it.
    /// For multiSelect, `answer` may be a list of ACCEPTABLE selections
    /// (list of lists) rather than a selection itself — submit the first one.
    private func validSubmission(for question: [String: Any]) throws -> Any {
        let answer = try XCTUnwrap(question["answer"])
        guard try bridge.questionAnswerType(question: question) == "multiSelect",
              let alternatives = answer as? [[Any]] else {
            return answer
        }
        return alternatives.first ?? answer
    }

    func testEveryModeGeneratesAndAcceptsItsOwnAnswer() throws {
        try bridge.setBankItems([])
        for mode in try bridge.modes() {
            for level in [1, 5] {
                let question = try bridge.generateQuestion(mode: mode, level: level)
                XCTAssertNotNil(question["answer"], "\(mode) L\(level) generated no answer")
                let correct = try bridge.checkAnswer(question: question, submitted: validSubmission(for: question))
                XCTAssertTrue(correct, "\(mode) L\(level): checkAnswer rejected its own answer")
            }
        }
    }

    /// Mirrors the JS suite's contract (choiceGeneration.spec.js): choices
    /// include the correct answer, contain no duplicates, and distractors
    /// score false through checkAnswer.
    func testChoiceQuestionsScoreDistractorsFalse() throws {
        try bridge.setBankItems([])
        var checkedDistractors = 0
        for mode in try bridge.modes() {
            let question = try bridge.generateQuestion(mode: mode, level: 2)
            guard try bridge.questionAnswerType(question: question) == "choice",
                  let answer = question["answer"] else { continue }
            let choices = try bridge.generateChoices(answer: answer, count: 4, question: question)
            XCTAssertGreaterThanOrEqual(choices.count, 2, "\(mode): expected at least 2 choices")
            XCTAssertLessThanOrEqual(choices.count, 4, "\(mode): expected at most 4 choices")
            for choice in choices {
                let correct = try bridge.checkAnswer(question: question, submitted: choice)
                if !correct { checkedDistractors += 1 }
            }
        }
        XCTAssertGreaterThan(checkedDistractors, 0, "no distractor ever scored false — checkAnswer looks broken")
    }

    // MARK: - Adaptive session end to end

    func testAdaptiveSessionFlowCompletes() throws {
        try bridge.setBankItems([])
        let session = try bridge.createSession(
            mode: "addition",
            sessionSize: 5,
            options: ["allowWordProblems": false]
        )
        XCTAssertEqual(session.snapshot["mode"] as? String, "addition")

        var answered = 0
        while try !bridge.isSessionComplete(session) {
            let (question, isRetry) = try bridge.nextQuestion(in: session)
            let outcome = try bridge.recordAnswer(
                in: session,
                question: question,
                answer: question["answer"]!,
                responseTimeMs: 1500,
                wasRetry: isRetry
            )
            XCTAssertTrue(outcome.correct, "engine rejected its own answer mid-session")
            answered += 1
            XCTAssertLessThan(answered, 20, "session never completed")
        }
        XCTAssertEqual(session.snapshot["questionsAnswered"] as? Int, 5)
        XCTAssertEqual(session.snapshot["firstTryCorrect"] as? Int, 5)
    }

    func testSessionResumesFromInjectedProgress() throws {
        let session = try bridge.createSession(
            mode: "multiplication",
            sessionSize: 5,
            options: ["savedProgress": ["level": 6, "mistakeBank": [], "bankItemStats": [:], "recentBankItemIds": []]]
        )
        XCTAssertEqual(session.snapshot["level"] as? Int, 6, "savedProgress.level was not honored")
    }

    // MARK: - Node parity (the core P0 guarantee)

    /// Fixtures are questions generated by the SAME bundle running in Node
    /// with a seeded Math.random (scripts/generateParityFixtures.mjs). Reseed
    /// JSC identically and the output must be byte-identical JSON.
    func testNodeParityFixtures() throws {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "engineParityFixtures", withExtension: "json"),
            "fixtures missing — run: node scripts/generateParityFixtures.mjs"
        )
        let payload = try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        let fixtures = try XCTUnwrap(payload?["fixtures"] as? [[String: Any]])
        XCTAssertGreaterThanOrEqual(fixtures.count, 60)

        try bridge.setBankItems([])
        for fixture in fixtures {
            let mode = fixture["mode"] as! String
            let level = fixture["level"] as! Int
            let seed = UInt32(fixture["seed"] as! Int)
            let expectedJSON = fixture["expectedJSON"] as! String

            try bridge.reseedRandom(seed)
            let actualJSON = try bridge.generateQuestionJSON(mode: mode, level: level)
            XCTAssertEqual(
                actualJSON, expectedJSON,
                "JSC output diverged from Node for \(mode) L\(level) seed \(seed)"
            )
        }
    }
}
