// Shared codegen for the split item-bank layout (Phase 0.4).
//
// The former ~6,500-line src/itemBank/applicationItems.js held every item.
// It is now a thin aggregator that imports per-mode data files from
// src/itemBank/items/<mode>.js. This module owns the file-writing so both the
// one-shot split (scripts/splitItemBank.js) and the cloud export
// (scripts/exportCloudBank.js) emit the exact same layout.

import { writeFileSync, mkdirSync, readdirSync, unlinkSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ITEM_BANK_DIR = resolve(__dirname, "../../src/itemBank");
const ITEMS_DIR = resolve(ITEM_BANK_DIR, "items");
const APP_FILE = resolve(ITEM_BANK_DIR, "applicationItems.js");

// Render one item as a readable JS object literal. Every field is preserved in
// its original key order (no whitelist, so optional fields like `source` are
// never dropped); values are compact JSON. `reviewStatus: "approved"` renders
// via the APPROVED constant to keep the files DRY and diff-friendly.
function itemLiteral(item) {
  const lines = Object.keys(item).map((key) => {
    if (key === "reviewStatus" && item[key] === "approved") {
      return "    reviewStatus: APPROVED,";
    }
    return `    ${key}: ${JSON.stringify(item[key])},`;
  });
  return `  {\n${lines.join("\n")}\n  }`;
}

// mode id -> import alias (mode ids are already identifier-safe).
function modeVar(mode) {
  return `${mode.replace(/[^a-zA-Z0-9]/g, "_")}Items`;
}

// Write per-mode files under ./items/ + the aggregator applicationItems.js.
// `items` is the ordered item array; modes are emitted in first-appearance
// order so the aggregated APPLICATION_ITEM_BANK is deterministic.
export function writeSplitBank(items) {
  const order = [];
  const byMode = new Map();
  for (const item of items) {
    if (!byMode.has(item.modeId)) {
      byMode.set(item.modeId, []);
      order.push(item.modeId);
    }
    byMode.get(item.modeId).push(item);
  }

  mkdirSync(ITEMS_DIR, { recursive: true });
  if (existsSync(ITEMS_DIR)) {
    for (const f of readdirSync(ITEMS_DIR)) {
      if (f.endsWith(".js")) unlinkSync(resolve(ITEMS_DIR, f));
    }
  }

  for (const mode of order) {
    const body = byMode.get(mode).map(itemLiteral).join(",\n");
    const content =
      `// Auto-generated item data for mode "${mode}". Do not hand-edit; regenerate\n` +
      `// via \`npm run bank:split\` or \`npm run bank:export\`.\n\n` +
      `import { APPROVED } from "../reviewStatus.js";\n\n` +
      `export const ITEMS = [\n${body},\n];\n`;
    writeFileSync(resolve(ITEMS_DIR, `${mode}.js`), content, "utf8");
  }

  const imports = order
    .map((m) => `import { ITEMS as ${modeVar(m)} } from "./items/${m}.js";`)
    .join("\n");
  const spread = order.map((m) => `  ...${modeVar(m)},`).join("\n");
  const app =
    `// Aggregator for the item bank. Item data lives in the per-mode files under\n` +
    `// ./items/ (split out of the former monolith in Phase 0.4). REVIEW_STATUS is\n` +
    `// re-exported for back-compat with existing importers.\n` +
    `//\n` +
    `// Auto-generated by scripts/lib/itemBankFiles.js — do not hand-edit.\n\n` +
    `export { REVIEW_STATUS } from "./reviewStatus.js";\n\n` +
    `${imports}\n\n` +
    `export const APPLICATION_ITEM_BANK = [\n${spread}\n];\n`;
  writeFileSync(APP_FILE, app, "utf8");

  return { modeOrder: order, counts: Object.fromEntries(order.map((m) => [m, byMode.get(m).length])) };
}
