#!/usr/bin/env node
/**
 * Build the seeded (bundled) item bank.
 *
 * The bundle previously carried every curated item — 1.4 MB of a 1.9 MB app —
 * so a child downloaded 22 modes' questions before answering one. This selects
 * a small, evenly spread subset to ship, and `modeLoader.ensureModeLoaded()`
 * fetches the rest of a mode when the child actually opens it.
 *
 * The seed is not arbitrary. It guarantees every (mode, family, level band)
 * cell has something, so the app works offline and on first paint in EVERY
 * mode, and the child never sees an empty cell while the fetch is in flight.
 *
 * Usage:
 *   npm run bank:seed:build              write the seed
 *   npm run bank:seed:build -- --per 3   items per cell (default 8)
 *   npm run bank:seed:build -- --dry     report the size, write nothing
 */

import { writeFileSync } from "node:fs";
// Read the FULL corpus, never bundle.js — that now exports this script's own
// output, and seeding from the seed would silently shrink it on every run.
import { FULL_ITEMS as BUNDLED_ITEMS } from "../src/itemBank/fullBank.js";

const args = process.argv.slice(2);
// Default 8 to match RECENT_BANK_WINDOW in mathEngine: the session engine
// avoids repeating within the last 8 items, so a cell holding fewer than that
// cannot satisfy the cooldown and an OFFLINE child would see repeats.
const perCell = Number(args.includes("--per") ? args[args.indexOf("--per") + 1] : 8);
const dryRun = args.includes("--dry");

const bandOf = (item) => {
  const [min] = item.levelRange || [1];
  return min <= 3 ? "K-1" : min <= 6 ? "2-3" : "4-5";
};

const cellKey = (item) => `${item.modeId}::${item.itemFamily}::${bandOf(item)}`;

function buildSeed(items, n) {
  const byCell = new Map();
  for (const item of items) {
    const key = cellKey(item);
    if (!byCell.has(key)) byCell.set(key, []);
    byCell.get(key).push(item);
  }

  const seed = [];
  for (const [, group] of byCell) {
    // Spread the picks across the group rather than taking the first n, so the
    // seed is not all one context: items were authored in runs.
    const step = Math.max(1, Math.floor(group.length / n));
    for (let i = 0, taken = 0; i < group.length && taken < n; i += step, taken += 1) {
      seed.push(group[i]);
    }
  }
  return { seed, cells: byCell.size };
}

const { seed, cells } = buildSeed(BUNDLED_ITEMS, perCell);

const fullBytes = Buffer.byteLength(JSON.stringify(BUNDLED_ITEMS));
const seedBytes = Buffer.byteLength(JSON.stringify(seed));
const pct = ((seedBytes / fullBytes) * 100).toFixed(1);

process.stdout.write(
  `\nSEED BANK\n` +
    `  cells covered      ${cells}\n` +
    `  items  ${BUNDLED_ITEMS.length} -> ${seed.length}  (${perCell}/cell)\n` +
    `  bytes  ${(fullBytes / 1024).toFixed(0)} KB -> ${(seedBytes / 1024).toFixed(0)} KB  (${pct}%)\n\n`
);

// Every cell must survive, or a mode could open with nothing to show while the
// fetch is in flight.
const seededCells = new Set(seed.map(cellKey));
const missing = [...new Set(BUNDLED_ITEMS.map(cellKey))].filter((c) => !seededCells.has(c));
if (missing.length) {
  process.stderr.write(`ERROR: ${missing.length} cell(s) have no seed item:\n  ${missing.join("\n  ")}\n`);
  process.exit(1);
}

if (dryRun) {
  process.stdout.write("(dry run — nothing written)\n");
  process.exit(0);
}

const header = `// AUTO-GENERATED by scripts/buildSeedBank.js — do not hand-edit.
//
// A small, evenly spread subset of the curated bank: ${perCell} item(s) per
// (mode, family, band) cell, so every mode works offline and on first paint.
// The rest of a mode's items are fetched by modeLoader.ensureModeLoaded() when
// the child opens that mode.
//
// Regenerate with: npm run bank:seed:build

export const SEED_ITEMS = ${JSON.stringify(seed, null, 1)};
`;

writeFileSync(new URL("../src/itemBank/seedItems.js", import.meta.url), header);
process.stdout.write(`wrote src/itemBank/seedItems.js (${seed.length} items)\n\n`);
