#!/usr/bin/env node
/* Snapshot the live cloud item bank into src/itemBank/applicationItems.js
 * so the bundled fallback stays current.
 *
 * Usage:
 *   VITE_SUPABASE_URL=... VITE_SUPABASE_ANON_KEY=... npm run bank:export
 *
 * Requires read access to public.item_bank where review_status='approved'.
 * Anonymous role works because of the SELECT-approved-for-authenticated
 * policy plus the public anon role. If your project restricts that, run
 * with a service role key in SUPABASE_SERVICE_ROLE_KEY instead.
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "@supabase/supabase-js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(__dirname, "../src/itemBank/applicationItems.js");

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.VITE_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error(
    "Missing Supabase credentials. Set VITE_SUPABASE_URL and either SUPABASE_SERVICE_ROLE_KEY or VITE_SUPABASE_ANON_KEY."
  );
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

function rowToItem(row) {
  return {
    itemId: row.item_id,
    modeId: row.mode_id,
    itemFamily: row.item_family || "application",
    subskill: row.subskill,
    structureType: row.structure_type,
    levelRange: [Number(row.level_min), Number(row.level_max)],
    reviewStatus: row.review_status,
    question: row.payload,
  };
}

function jsLiteral(item) {
  return `  {
    itemId: ${JSON.stringify(item.itemId)},
    modeId: ${JSON.stringify(item.modeId)},
    itemFamily: ${JSON.stringify(item.itemFamily)},
    subskill: ${JSON.stringify(item.subskill)},
    structureType: ${JSON.stringify(item.structureType)},
    levelRange: [${item.levelRange[0]}, ${item.levelRange[1]}],
    reviewStatus: APPROVED,
    question: ${JSON.stringify(item.question, null, 4).replace(/\n/g, "\n    ")},
  }`;
}

async function main() {
  const { data, error } = await supabase
    .from("item_bank")
    .select(
      "item_id, mode_id, item_family, subskill, structure_type, level_min, level_max, review_status, payload"
    )
    .eq("review_status", "approved")
    .order("mode_id", { ascending: true })
    .order("item_id", { ascending: true });

  if (error) {
    console.error("Failed to fetch from item_bank:", error.message);
    process.exit(1);
  }
  if (!data || data.length === 0) {
    console.error("No approved items returned. Aborting export to avoid wiping the bundle.");
    process.exit(1);
  }

  const items = data.map(rowToItem);
  const header =
    "// Auto-generated by scripts/exportCloudBank.js. Do not edit by hand;\n" +
    "// run `npm run bank:export` after approving items in the admin UI.\n\n" +
    'export const REVIEW_STATUS = {\n  DRAFT: "draft",\n  REVIEWED: "reviewed",\n' +
    '  APPROVED: "approved",\n  RETIRED: "retired",\n};\n\n' +
    "const APPROVED = REVIEW_STATUS.APPROVED;\n\n" +
    "export const APPLICATION_ITEM_BANK = [\n";
  const body = items.map(jsLiteral).join(",\n");
  const footer = ",\n];\n";

  writeFileSync(TARGET, header + body + footer, "utf8");
  console.log(`Wrote ${items.length} items to ${TARGET}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
