#!/usr/bin/env node
// Copy the Meadow art kit (public/meadow/**.webp, the web's source of truth)
// into the iOS bundle as loose resources — Xcode's asset compiler rejects
// WebP ("not a valid extension"), but ImageIO decodes it at runtime, so the
// files ship as-is at 1.9 MB — and emit the size manifest as Swift.
// Idempotent; run after the art changes:  npm run ios:art
// Files land flat as meadow-<group>-<id>.webp (XcodeGen copies the Resources
// folder without subdirectories) and are committed: the app ships them.
import { readdirSync, mkdirSync, copyFileSync, writeFileSync, rmSync, readFileSync } from "node:fs";
import { resolve, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = resolve(root, "public/meadow");
const out = resolve(root, "ios/KidMath/Resources/meadow");
const manifest = JSON.parse(readFileSync(resolve(root, "src/engagement/meadow/artManifest.json"), "utf8"));

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

let count = 0;
for (const group of readdirSync(src)) {
  for (const file of readdirSync(resolve(src, group))) {
    if (extname(file) !== ".webp") continue;
    copyFileSync(resolve(src, group, file), resolve(out, `meadow-${group}-${basename(file, ".webp")}.webp`));
    count += 1;
  }
}

// Swift manifest: intrinsic sizes so views can fit by aspect like the web.
const lines = [
  "// GENERATED by scripts/syncMeadowArt.mjs from src/engagement/meadow/artManifest.json — do not edit.",
  "import CoreGraphics",
  "",
  "enum MeadowArtManifest {",
  "    static let sizes: [String: CGSize] = [",
];
for (const [group, entries] of Object.entries(manifest)) {
  for (const [id, m] of Object.entries(entries)) {
    lines.push(`        "${group}/${id}": CGSize(width: ${m.w}, height: ${m.h}),`);
  }
}
lines.push("    ]", "}", "");
writeFileSync(resolve(root, "ios/KidMath/Services/MeadowArtManifest.swift"), lines.join("\n"));
console.log(`Synced ${count} Meadow images into ios/KidMath/Resources/meadow and wrote MeadowArtManifest.swift`);
