/* Worksheet skill audit — the menu worksheet skills are authored from.
 *
 * Worksheets draw from the curated bank, so a "skill" (what a parent picks:
 * "Tell time to the hour and half hour") is a filter over bank cells. This
 * script lists every cell — mode × family × subskill × structureType ×
 * levelRange — with how many of its items survive the paper rules, what they
 * look like on a sheet, and how big their numbers are. Read skills off this
 * table; never guess them.
 *
 *   node --import ./scripts/lib/registerResolve.js scripts/worksheetAudit.mjs
 *     [--mode time]      one mode only
 *     [--md]             write docs/worksheet-skill-audit.md instead of stdout
 *
 * Read-only: touches neither the bank nor Supabase.
 */
import { writeFileSync } from "node:fs";
import { FULL_ITEMS } from "../src/itemBank/fullBank.js";
import { buildQuestionFromBankItem } from "../src/itemBank/index.js";
import {
  isPrintablePrompt,
  isPureComputation,
  isYesNoJudgment,
  printableWording,
  printOptionBank,
} from "../src/mathEngine.js";
import { MODE_IDS } from "../src/modes/index.js";

const args = process.argv.slice(2);
const onlyMode = args.includes("--mode") ? args[args.indexOf("--mode") + 1] : null;
const asMarkdown = args.includes("--md");

// Bank payloads spell operators several ways ("−", "×", "÷"); the engine's
// pure-computation test wants the ASCII ones.
const ASCII_OP = { "−": "-", "×": "x", "÷": "/" };

function printable(item) {
  const built = buildQuestionFromBankItem(item, item.levelRange?.[0] ?? 1);
  if (!built) return null;
  const q = printableWording({ ...built, op: ASCII_OP[built.op] || built.op });
  return isPrintablePrompt(q) ? q : null;
}

function promptNumbers(q) {
  const fromPayload = [q.a, q.b, q.answer].filter((n) => typeof n === "number");
  const fromText = (q.display?.promptText || "").match(/\d+(?:\.\d+)?/g)?.map(Number) || [];
  return [...fromPayload, ...fromText];
}

function sizeBucket(max) {
  if (max <= 10) return "≤10";
  if (max <= 20) return "≤20";
  if (max <= 100) return "≤100";
  if (max <= 1000) return "≤1000";
  return ">1000";
}

function sheetForm(q) {
  if (q.display?.figure) return "figure";
  if (isYesNoJudgment(q)) return "yes/no";
  if (printOptionBank(q)) return "options";
  if (isPureComputation(q)) return "a op b";
  return typeof q.answer === "number" ? "number" : "text";
}

function tally(map, key) {
  map.set(key, (map.get(key) || 0) + 1);
}

function summarize(map) {
  return [...map.entries()]
    .sort((x, y) => y[1] - x[1])
    .map(([k, n]) => `${k}×${n}`)
    .join(" ");
}

const cells = new Map();
for (const item of FULL_ITEMS) {
  if (onlyMode && item.modeId !== onlyMode) continue;
  const range = (item.levelRange || []).join("–");
  const key = [item.modeId, item.itemFamily, item.subskill, item.structureType || "—", range].join("|");
  let cell = cells.get(key);
  if (!cell) {
    cell = { total: 0, printable: 0, forms: new Map(), sizes: new Map(), promptChars: 0, samples: [] };
    cells.set(key, cell);
  }
  cell.total++;
  const q = printable(item);
  if (!q) continue;
  cell.printable++;
  tally(cell.forms, sheetForm(q));
  const numbers = promptNumbers(q);
  if (numbers.length) tally(cell.sizes, sizeBucket(Math.max(...numbers)));
  const text = q.display?.promptText || "";
  cell.promptChars += text.length;
  if (cell.samples.length < 2 && text) cell.samples.push(text.length > 90 ? `${text.slice(0, 87)}…` : text);
}

const lines = [];
const modes = onlyMode ? [onlyMode] : MODE_IDS;
let thin = 0;
for (const mode of modes) {
  const rows = [...cells.entries()]
    .filter(([key]) => key.startsWith(`${mode}|`))
    .sort(([x], [y]) => x.localeCompare(y));
  const total = rows.reduce((n, [, c]) => n + c.total, 0);
  const printableTotal = rows.reduce((n, [, c]) => n + c.printable, 0);
  lines.push(`## ${mode} — ${rows.length} cells, ${printableTotal}/${total} items printable`, "");
  lines.push("| family | subskill | structure | levels | items | printable | on the sheet | number size | avg chars | samples |");
  lines.push("|---|---|---|---|---|---|---|---|---|---|");
  for (const [key, c] of rows) {
    const [, family, subskill, structure, range] = key.split("|");
    if (c.printable < 6) thin++;
    lines.push(
      `| ${family} | ${subskill} | ${structure} | ${range} | ${c.total} | ${c.printable} | ${summarize(c.forms)} | ${summarize(c.sizes)} | ${
        c.printable ? Math.round(c.promptChars / c.printable) : "—"
      } | ${c.samples.map((s) => s.replace(/\|/g, "\\|")).join(" ⏎ ")} |`
    );
  }
  lines.push("");
}

const header = [
  "# Worksheet skill audit",
  "",
  "Generated by `scripts/worksheetAudit.mjs` — do not hand-edit. One row per bank cell;",
  "`printable` is what survives the paper rules (no screen verbs, no answer printed in",
  "its own prompt, no multiSelect/tenFrame). A worksheet skill groups 2–5 of these rows.",
  "",
  `${FULL_ITEMS.length} bank items · ${cells.size} cells · ${thin} cells with fewer than 6 printable items`,
  "",
];
const out = [...header, ...lines].join("\n");

if (asMarkdown) {
  const path = new URL("../docs/worksheet-skill-audit.md", import.meta.url);
  writeFileSync(path, out);
  console.log(`wrote docs/worksheet-skill-audit.md — ${cells.size} cells, ${thin} thin`);
} else {
  console.log(out);
}
