// Auto-generated item data for mode "comparing". Do not hand-edit; regenerate
// via `npm run bank:split` or `npm run bank:export`.

import { APPROVED } from "../reviewStatus.js";

export const ITEMS = [
  {
    itemId: "comparing-app-001",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":246,"b":264,"op":"?","answer":"<","display":{"promptText":"Lane A scored 246 points and Lane B scored 264 points. Which symbol compares Lane A to Lane B?"}},
  },
  {
    itemId: "comparing-app-002",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":178,"b":187,"op":"?","answer":"<","display":{"promptText":"A class read 178 books and another class read 187 books. Which symbol compares 178 to 187?"}},
  },
  {
    itemId: "comparing-app-003",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":510,"b":499,"op":"?","answer":">","display":{"promptText":"A library counted 510 books on one shelf and 499 on another. Which symbol compares 510 to 499?"}},
  },
  {
    itemId: "comparing-app-004",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":805,"b":850,"op":"?","answer":"<","display":{"promptText":"A stadium seats 805 fans and a theater seats 850 fans. Which symbol compares 805 to 850?"}},
  },
  {
    itemId: "comparing-app-005",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":380,"b":380,"op":"?","answer":"=","display":{"promptText":"Two classes each solved 380 puzzles this month. Which symbol compares the totals?"}},
  },
  {
    itemId: "comparing-app-006",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":612,"b":612,"op":"?","answer":"=","display":{"promptText":"Town A and Town B each have 612 students. Which symbol compares the two amounts?"}},
  },
  {
    itemId: "comparing-app-007",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":84,"b":79,"op":"?","answer":">","display":{"promptText":"A class read 84 books and another class read 79 books. Which symbol compares 84 to 79?"}},
  },
  {
    itemId: "comparing-app-008",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":999,"b":1001,"op":"?","answer":"<","display":{"promptText":"A counter shows 999 in one window and 1001 in another. Which symbol compares 999 to 1001?"}},
  },
  {
    itemId: "comparing-app-009",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":145,"b":145,"op":"?","answer":"=","display":{"promptText":"Two food drives each collected 145 cans. Which symbol compares the two totals?"}},
  },
  {
    itemId: "comparing-app-010",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":432,"b":423,"op":"?","answer":">","display":{"promptText":"A movie sold 432 tickets and a play sold 423. Which symbol compares 432 to 423?"}},
  },
  {
    itemId: "comparing-app-011",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":250,"b":205,"op":"?","answer":">","display":{"promptText":"A pool has 250 swim laps logged and another has 205. Which symbol compares 250 to 205?"}},
  },
  {
    itemId: "comparing-app-012",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":720,"b":720,"op":"?","answer":"=","display":{"promptText":"Two schools each enrolled 720 students. Which symbol compares the two enrollments?"}},
  },
  {
    itemId: "comparing-app-013",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":304,"b":340,"op":"?","answer":"<","display":{"promptText":"A garden has 304 tulips and 340 daisies. Which symbol compares 304 to 340?"}},
  },
  {
    itemId: "comparing-app-014",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":8,"op":"?","answer":"<","display":{"promptText":"Mia has 5 candies. Tom has 8 candies. Which symbol compares 5 to 8?"}},
  },
  {
    itemId: "comparing-app-015",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":4,"op":"?","answer":">","display":{"promptText":"Sara counted 7 cars. Eli counted 4 cars. Which symbol compares 7 to 4?"}},
  },
  {
    itemId: "comparing-app-016",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":6,"op":"?","answer":"=","display":{"promptText":"Two boxes both have 6 toys. Which symbol compares 6 to 6?"}},
  },
  {
    itemId: "comparing-app-017",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":5,"op":"?","answer":"<","display":{"promptText":"A jar holds 4 marbles. The benchmark is 5. Compare 4 to 5."}},
  },
  {
    itemId: "comparing-app-018",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":5,"op":"?","answer":">","display":{"promptText":"Lia has 7 stickers; the benchmark is 5. Compare 7 to 5."}},
  },
  {
    itemId: "comparing-app-019",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":10,"op":"?","answer":"=","display":{"promptText":"Both Sam and Pat have 10 grapes. Compare 10 to 10."}},
  },
  {
    itemId: "comparing-app-020",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":4,"op":"?","answer":">","display":{"promptText":"Eli has 9 apples and Mia has 4. Compare 9 to 4."}},
  },
  {
    itemId: "comparing-app-021",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":3,"b":8,"op":"?","answer":"<","display":{"promptText":"Min has 3 pens and Tom has 8 pens. Compare 3 to 8."}},
  },
  {
    itemId: "comparing-app-022",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":6,"op":"?","answer":"=","display":{"promptText":"Jin has 6 hats and Pat has 6 hats. Compare 6 to 6."}},
  },
  {
    itemId: "comparing-app-023",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":23,"b":45,"op":"?","answer":"<","display":{"promptText":"A class has 23 books. Another class has 45 books. Compare 23 and 45."}},
  },
  {
    itemId: "comparing-app-024",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":67,"b":32,"op":"?","answer":">","display":{"promptText":"Pat scored 67 points and Min scored 32 points. Compare 67 and 32."}},
  },
  {
    itemId: "comparing-app-025",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":50,"b":50,"op":"?","answer":"=","display":{"promptText":"Two teams both have 50 fans. Compare 50 and 50."}},
  },
  {
    itemId: "comparing-app-026",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":47,"b":50,"op":"?","answer":"<","display":{"promptText":"A factory made 47 toys; the goal was 50. Compare 47 and 50."}},
  },
  {
    itemId: "comparing-app-027",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":65,"b":50,"op":"?","answer":">","display":{"promptText":"A book has 65 pages. The library asks for at least 50. Compare 65 and 50."}},
  },
  {
    itemId: "comparing-app-028",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":30,"op":"?","answer":"=","display":{"promptText":"Both jars hold 30 jellybeans. Compare 30 and 30."}},
  },
  {
    itemId: "comparing-app-029",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":25,"op":"?","answer":"<","display":{"promptText":"Anna ran 18 laps and Ben ran 25 laps. Compare 18 and 25."}},
  },
  {
    itemId: "comparing-app-030",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":75,"b":42,"op":"?","answer":">","display":{"promptText":"A garden has 75 tulips and 42 daisies. Compare 75 and 42."}},
  },
  {
    itemId: "comparing-app-031",
    modeId: "comparing",
    itemFamily: "application",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":60,"b":60,"op":"?","answer":"=","display":{"promptText":"Two ponds each have 60 ducks. Compare 60 and 60."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-K1-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":8,"op":"?","answer":"<","display":{"promptText":"Compare 5 and 8 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-K1-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":4,"op":"?","answer":">","display":{"promptText":"Compare 7 and 4 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-K1-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":6,"op":"?","answer":"=","display":{"promptText":"Compare 6 and 6 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-23-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":23,"b":45,"op":"?","answer":"<","display":{"promptText":"Compare 23 and 45 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-23-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":67,"b":32,"op":"?","answer":">","display":{"promptText":"Compare 67 and 32 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-23-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":50,"b":50,"op":"?","answer":"=","display":{"promptText":"Compare 50 and 50 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-45-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":567,"op":"?","answer":"<","display":{"promptText":"Compare 234 and 567 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-45-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":891,"b":234,"op":"?","answer":">","display":{"promptText":"Compare 891 and 234 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-symbolSelection-45-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":345,"b":345,"op":"?","answer":"=","display":{"promptText":"Compare 345 and 345 with <, >, or =."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-K1-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":5,"op":"?","answer":"<","display":{"promptText":"Compare 4 and 5."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-K1-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":5,"op":"?","answer":">","display":{"promptText":"Compare 7 and 5."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-K1-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":10,"op":"?","answer":"=","display":{"promptText":"Compare 10 and 10."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-23-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":47,"b":50,"op":"?","answer":"<","display":{"promptText":"Compare 47 and 50."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-23-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":65,"b":50,"op":"?","answer":">","display":{"promptText":"Compare 65 and 50."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-23-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":30,"op":"?","answer":"=","display":{"promptText":"Compare 30 and 30."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-45-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":487,"b":500,"op":"?","answer":"<","display":{"promptText":"Compare 487 and 500."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-45-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":678,"b":500,"op":"?","answer":">","display":{"promptText":"Compare 678 and 500."}},
  },
  {
    itemId: "comparing-proc-benchmarkCompare-45-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":100,"op":"?","answer":"=","display":{"promptText":"Compare 100 and 100."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-K1-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":2,"b":9,"op":"?","answer":"<","display":{"promptText":"Compare 2 and 9."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-K1-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":1,"op":"?","answer":">","display":{"promptText":"Compare 8 and 1."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-K1-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":5,"op":"?","answer":"=","display":{"promptText":"Compare 5 and 5."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-23-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":25,"op":"?","answer":"<","display":{"promptText":"Compare 18 and 25."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-23-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":75,"b":42,"op":"?","answer":">","display":{"promptText":"Compare 75 and 42."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-23-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":60,"b":60,"op":"?","answer":"=","display":{"promptText":"Compare 60 and 60."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-45-001",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":156,"b":412,"op":"?","answer":"<","display":{"promptText":"Compare 156 and 412."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-45-002",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":789,"b":321,"op":"?","answer":">","display":{"promptText":"Compare 789 and 321."}},
  },
  {
    itemId: "comparing-proc-distanceCompare-45-003",
    modeId: "comparing",
    itemFamily: "procedural",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":200,"b":200,"op":"?","answer":"=","display":{"promptText":"Compare 200 and 200."}},
  },
  {
    itemId: "comparing-conc-symbolSelection-K1-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":8,"op":"?","answer":"<","display":{"promptText":"Looking at 5 and 8, which symbol shows that 5 is smaller?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-K1-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":4,"op":"?","answer":">","display":{"promptText":"Looking at 7 and 4, which symbol shows that 7 is greater?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-K1-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":6,"op":"?","answer":"=","display":{"promptText":"Looking at 6 and 6, are they equal?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-23-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":23,"b":45,"op":"?","answer":"<","display":{"promptText":"Looking at 23 and 45, which is smaller?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-23-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":67,"b":32,"op":"?","answer":">","display":{"promptText":"Looking at 67 and 32, which is greater?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-23-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":50,"b":50,"op":"?","answer":"=","display":{"promptText":"Looking at 50 and 50, are they equal?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-45-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":567,"op":"?","answer":"<","display":{"promptText":"Looking at 234 and 567, which is smaller?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-45-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":891,"b":234,"op":"?","answer":">","display":{"promptText":"Looking at 891 and 234, which is greater?"}},
  },
  {
    itemId: "comparing-conc-symbolSelection-45-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "symbolSelection",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":345,"b":345,"op":"?","answer":"=","display":{"promptText":"Looking at 345 and 345, are they equal?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-K1-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":5,"op":"?","answer":"<","display":{"promptText":"Use 5 as a benchmark: is 4 less than 5?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-K1-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":5,"op":"?","answer":">","display":{"promptText":"Use 5 as a benchmark: is 7 greater than 5?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-K1-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":10,"op":"?","answer":"=","display":{"promptText":"Use 10 as a benchmark: how does 10 compare to 10?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-23-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":47,"b":50,"op":"?","answer":"<","display":{"promptText":"Use 50 as a benchmark: is 47 less than 50?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-23-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":65,"b":50,"op":"?","answer":">","display":{"promptText":"Use 50 as a benchmark: is 65 greater than 50?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-23-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":30,"op":"?","answer":"=","display":{"promptText":"Use 30 as a benchmark: how does 30 compare to 30?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-45-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":487,"b":500,"op":"?","answer":"<","display":{"promptText":"Use 500 as a benchmark: is 487 less than 500?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-45-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":678,"b":500,"op":"?","answer":">","display":{"promptText":"Use 500 as a benchmark: is 678 greater than 500?"}},
  },
  {
    itemId: "comparing-conc-benchmarkCompare-45-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "benchmarkCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":100,"op":"?","answer":"=","display":{"promptText":"Use 100 as a benchmark: how does 100 compare to 100?"}},
  },
  {
    itemId: "comparing-conc-distanceCompare-K1-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":2,"b":9,"op":"?","answer":"<","display":{"promptText":"On a number line, which is to the left: 2 or 9?"}},
  },
  {
    itemId: "comparing-conc-distanceCompare-K1-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":1,"op":"?","answer":">","display":{"promptText":"On a number line, which is to the right: 8 or 1?"}},
  },
  {
    itemId: "comparing-conc-distanceCompare-K1-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":5,"op":"?","answer":"=","display":{"promptText":"5 and 5 sit at the same point on a number line. Compare them."}},
  },
  {
    itemId: "comparing-conc-distanceCompare-23-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":25,"op":"?","answer":"<","display":{"promptText":"On a number line, 18 is closer to 0 than 25. Compare 18 and 25."}},
  },
  {
    itemId: "comparing-conc-distanceCompare-23-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":75,"b":42,"op":"?","answer":">","display":{"promptText":"On a number line, 75 is farther from 0 than 42. Compare 75 and 42."}},
  },
  {
    itemId: "comparing-conc-distanceCompare-23-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":60,"b":60,"op":"?","answer":"=","display":{"promptText":"60 and 60 sit at the same point on a number line. Compare them."}},
  },
  {
    itemId: "comparing-conc-distanceCompare-45-001",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":156,"b":412,"op":"?","answer":"<","display":{"promptText":"On a number line, 156 is to the left of 412. Compare 156 and 412."}},
  },
  {
    itemId: "comparing-conc-distanceCompare-45-002",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":789,"b":321,"op":"?","answer":">","display":{"promptText":"On a number line, 789 is farther right than 321. Compare 789 and 321."}},
  },
  {
    itemId: "comparing-conc-distanceCompare-45-003",
    modeId: "comparing",
    itemFamily: "conceptual",
    subskill: "distanceCompare",
    structureType: "compareNumbers",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":200,"b":200,"op":"?","answer":"=","display":{"promptText":"200 and 200 sit at the same point on a number line. Compare them."}},
  },
];
