// Auto-generated item data for mode "counting". Do not hand-edit; regenerate
// via `npm run bank:split` or `npm run bank:export`.

import { APPROVED } from "../reviewStatus.js";

export const ITEMS = [
  {
    itemId: "counting-app-001",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":14,"b":null,"op":"count","answer":14,"display":{"promptText":"There are 14 toy cars lined up on a shelf. How many toy cars are there?"}},
  },
  {
    itemId: "counting-app-002",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":20,"b":null,"op":"count","answer":20,"display":{"promptText":"A box has 20 crayons inside. How many crayons are in the box?"}},
  },
  {
    itemId: "counting-app-003",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":27,"b":null,"op":"count","answer":27,"display":{"promptText":"A jar has 27 marbles. Count to find how many marbles are in the jar."}},
  },
  {
    itemId: "counting-app-004",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":42,"b":null,"op":"count","answer":42,"display":{"promptText":"A garden has 42 tulips. How many tulips are in the garden?"}},
  },
  {
    itemId: "counting-app-005",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"count","answer":35,"display":{"promptText":"A basket holds 35 oranges. How many oranges are in the basket?"}},
  },
  {
    itemId: "counting-app-006",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":50,"b":null,"op":"count","answer":50,"display":{"promptText":"A class collected 50 cans for recycling. How many cans were collected?"}},
  },
  {
    itemId: "counting-app-007",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"count","answer":18,"display":{"promptText":"A pencil case has 18 pencils. How many pencils are in the case?"}},
  },
  {
    itemId: "counting-app-008",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":31,"b":null,"op":"count","answer":31,"display":{"promptText":"A row has 31 chairs set up for a play. How many chairs are in the row?"}},
  },
  {
    itemId: "counting-app-009",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":38,"b":null,"op":"count","answer":38,"display":{"promptText":"A jar holds 38 cookies. How many cookies are in the jar?"}},
  },
  {
    itemId: "counting-app-010",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":24,"b":null,"op":"count","answer":24,"display":{"promptText":"A drawer has 24 spoons. How many spoons are in the drawer?"}},
  },
  {
    itemId: "counting-app-011",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":47,"b":null,"op":"count","answer":47,"display":{"promptText":"A wall has 47 photos hung up. How many photos are on the wall?"}},
  },
  {
    itemId: "counting-app-012",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":60,"b":null,"op":"count","answer":60,"display":{"promptText":"A box of building blocks has 60 pieces. How many pieces are in the box?"}},
  },
  {
    itemId: "counting-app-013",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":16,"b":null,"op":"count","answer":16,"display":{"promptText":"A garden has 16 sunflowers. How many sunflowers are in the garden?"}},
  },
  {
    itemId: "counting-app-014",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":null,"op":"count","answer":4,"display":{"promptText":"There are 4 ducks in the pond. How many ducks are there?"}},
  },
  {
    itemId: "counting-app-015",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":null,"op":"count","answer":5,"display":{"promptText":"Mia drew 5 stars on her paper. How many stars did she draw?"}},
  },
  {
    itemId: "counting-app-016",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":3,"b":null,"op":"count","answer":3,"display":{"promptText":"A small bowl has 3 fish. How many fish are in the bowl?"}},
  },
  {
    itemId: "counting-app-017",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":null,"op":"count","answer":6,"display":{"promptText":"Tim counts 4 birds, then sees 2 more land. How many birds in total?"}},
  },
  {
    itemId: "counting-app-018",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":null,"op":"count","answer":7,"display":{"promptText":"Lin had 5 grapes; her brother gave her 2 more. How many grapes does Lin have?"}},
  },
  {
    itemId: "counting-app-019",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":null,"op":"count","answer":8,"display":{"promptText":"Sam saw 6 cars, then 2 more drove up. How many cars are there now?"}},
  },
  {
    itemId: "counting-app-020",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":null,"op":"count","answer":10,"display":{"promptText":"Anna lined up 10 small toys on the table. How many toys are in the line?"}},
  },
  {
    itemId: "counting-app-021",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":null,"op":"count","answer":8,"display":{"promptText":"A pencil case holds 8 erasers. How many erasers are in the case?"}},
  },
  {
    itemId: "counting-app-022",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":null,"op":"count","answer":9,"display":{"promptText":"A nest has 9 eggs in it. How many eggs are in the nest?"}},
  },
  {
    itemId: "counting-app-023",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"count","answer":18,"display":{"promptText":"A page has 18 stickers on it. How many stickers are on the page?"}},
  },
  {
    itemId: "counting-app-024",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":22,"b":null,"op":"count","answer":22,"display":{"promptText":"A team has 22 players. How many players are on the team?"}},
  },
  {
    itemId: "counting-app-025",
    modeId: "counting",
    itemFamily: "application",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":25,"b":null,"op":"count","answer":25,"display":{"promptText":"Sam saw 25 ants on the ground. How many ants did Sam see?"}},
  },
  {
    itemId: "counting-app-026",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":null,"op":"count","answer":30,"display":{"promptText":"Lia had 25 cubes, then added 5 more. How many cubes does Lia have now?"}},
  },
  {
    itemId: "counting-app-027",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"count","answer":35,"display":{"promptText":"A bin had 30 blocks; Pat added 5 more. How many blocks are in the bin now?"}},
  },
  {
    itemId: "counting-app-028",
    modeId: "counting",
    itemFamily: "application",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":40,"b":null,"op":"count","answer":40,"display":{"promptText":"Min counted 35 marbles, then 5 more rolled in. How many marbles in all?"}},
  },
  {
    itemId: "counting-app-029",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":28,"b":null,"op":"count","answer":28,"display":{"promptText":"A planter holds 28 tulips. How many tulips are in the planter?"}},
  },
  {
    itemId: "counting-app-030",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":32,"b":null,"op":"count","answer":32,"display":{"promptText":"A classroom has 32 desks. How many desks are in the classroom?"}},
  },
  {
    itemId: "counting-app-031",
    modeId: "counting",
    itemFamily: "application",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":null,"op":"count","answer":36,"display":{"promptText":"A book has 36 pages. How many pages are in the book?"}},
  },
  {
    itemId: "counting-proc-subitizing-K1-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":null,"op":"count","answer":4,"display":{"promptText":"Count: 1, 2, 3, 4. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-K1-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":null,"op":"count","answer":5,"display":{"promptText":"Count: 1, 2, 3, 4, 5. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-K1-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":3,"b":null,"op":"count","answer":3,"display":{"promptText":"Count: 1, 2, 3. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-23-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"count","answer":18,"display":{"promptText":"Count from 1 to 18. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-23-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":22,"b":null,"op":"count","answer":22,"display":{"promptText":"Count from 1 to 22. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-23-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":25,"b":null,"op":"count","answer":25,"display":{"promptText":"Count from 1 to 25. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-45-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":50,"b":null,"op":"count","answer":50,"display":{"promptText":"Count from 1 to 50. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-45-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":75,"b":null,"op":"count","answer":75,"display":{"promptText":"Count from 1 to 75. What is the count?"}},
  },
  {
    itemId: "counting-proc-subitizing-45-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":null,"op":"count","answer":100,"display":{"promptText":"Count from 1 to 100. What is the count?"}},
  },
  {
    itemId: "counting-proc-countOn-K1-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":null,"op":"count","answer":6,"display":{"promptText":"Start at 4 and count on 2. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-K1-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":null,"op":"count","answer":7,"display":{"promptText":"Start at 5 and count on 2. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-K1-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":null,"op":"count","answer":8,"display":{"promptText":"Start at 6 and count on 2. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-23-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":null,"op":"count","answer":30,"display":{"promptText":"Start at 25 and count on 5. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-23-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"count","answer":35,"display":{"promptText":"Start at 30 and count on 5. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-23-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":40,"b":null,"op":"count","answer":40,"display":{"promptText":"Start at 35 and count on 5. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-45-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":60,"b":null,"op":"count","answer":60,"display":{"promptText":"Start at 50 and count on 10. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-45-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":80,"b":null,"op":"count","answer":80,"display":{"promptText":"Start at 75 and count on 5. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-countOn-45-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":null,"op":"count","answer":100,"display":{"promptText":"Start at 90 and count on 10. What number do you reach?"}},
  },
  {
    itemId: "counting-proc-cardinality-K1-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":null,"op":"count","answer":10,"display":{"promptText":"Count 10 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-K1-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":null,"op":"count","answer":8,"display":{"promptText":"Count 8 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-K1-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":null,"op":"count","answer":9,"display":{"promptText":"Count 9 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-23-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":28,"b":null,"op":"count","answer":28,"display":{"promptText":"Count 28 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-23-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":32,"b":null,"op":"count","answer":32,"display":{"promptText":"Count 32 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-23-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":null,"op":"count","answer":36,"display":{"promptText":"Count 36 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-45-001",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":50,"b":null,"op":"count","answer":50,"display":{"promptText":"Count 50 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-45-002",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":75,"b":null,"op":"count","answer":75,"display":{"promptText":"Count 75 items. The cardinality is?"}},
  },
  {
    itemId: "counting-proc-cardinality-45-003",
    modeId: "counting",
    itemFamily: "procedural",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":null,"op":"count","answer":100,"display":{"promptText":"Count 100 items. The cardinality is?"}},
  },
  {
    itemId: "counting-conc-subitizing-K1-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":null,"op":"count","answer":4,"display":{"promptText":"A small set of 4 dots. Subitize the count."}},
  },
  {
    itemId: "counting-conc-subitizing-K1-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":5,"b":null,"op":"count","answer":5,"display":{"promptText":"A small set of 5 stars. Subitize the count."}},
  },
  {
    itemId: "counting-conc-subitizing-K1-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":3,"b":null,"op":"count","answer":3,"display":{"promptText":"A small set of 3 cubes. Subitize the count."}},
  },
  {
    itemId: "counting-conc-subitizing-23-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"count","answer":18,"display":{"promptText":"A medium set of 18 dots. What is the count?"}},
  },
  {
    itemId: "counting-conc-subitizing-23-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":22,"b":null,"op":"count","answer":22,"display":{"promptText":"A medium set of 22 dots. What is the count?"}},
  },
  {
    itemId: "counting-conc-subitizing-23-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":25,"b":null,"op":"count","answer":25,"display":{"promptText":"A medium set of 25 dots. What is the count?"}},
  },
  {
    itemId: "counting-conc-subitizing-45-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":50,"b":null,"op":"count","answer":50,"display":{"promptText":"A large set of 50 items. The count is?"}},
  },
  {
    itemId: "counting-conc-subitizing-45-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":75,"b":null,"op":"count","answer":75,"display":{"promptText":"A large set of 75 items. The count is?"}},
  },
  {
    itemId: "counting-conc-subitizing-45-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "subitizing",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":null,"op":"count","answer":100,"display":{"promptText":"A large set of 100 items. The count is?"}},
  },
  {
    itemId: "counting-conc-countOn-K1-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":null,"op":"count","answer":6,"display":{"promptText":"Use count-on from 4 to find 4 + 2."}},
  },
  {
    itemId: "counting-conc-countOn-K1-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":7,"b":null,"op":"count","answer":7,"display":{"promptText":"Use count-on from 5 to find 5 + 2."}},
  },
  {
    itemId: "counting-conc-countOn-K1-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":null,"op":"count","answer":8,"display":{"promptText":"Use count-on from 6 to find 6 + 2."}},
  },
  {
    itemId: "counting-conc-countOn-23-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":null,"op":"count","answer":30,"display":{"promptText":"Use count-on from 25 by 5s. After one step, what is the count?"}},
  },
  {
    itemId: "counting-conc-countOn-23-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"count","answer":35,"display":{"promptText":"Use count-on from 30 by 5s. After one step, what is the count?"}},
  },
  {
    itemId: "counting-conc-countOn-23-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":40,"b":null,"op":"count","answer":40,"display":{"promptText":"Use count-on from 35 by 5s. After one step, what is the count?"}},
  },
  {
    itemId: "counting-conc-countOn-45-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":60,"b":null,"op":"count","answer":60,"display":{"promptText":"Use count-on from 50 by 10s. After one step, what is the count?"}},
  },
  {
    itemId: "counting-conc-countOn-45-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":80,"b":null,"op":"count","answer":80,"display":{"promptText":"Use count-on from 75 by 5s. After one step, what is the count?"}},
  },
  {
    itemId: "counting-conc-countOn-45-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "countOn",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":null,"op":"count","answer":100,"display":{"promptText":"Use count-on from 90 by 10s. After one step, what is the count?"}},
  },
  {
    itemId: "counting-conc-cardinality-K1-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":null,"op":"count","answer":10,"display":{"promptText":"After counting all items in a set of 10, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-K1-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":null,"op":"count","answer":8,"display":{"promptText":"After counting all items in a set of 8, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-K1-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":null,"op":"count","answer":9,"display":{"promptText":"After counting all items in a set of 9, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-23-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":28,"b":null,"op":"count","answer":28,"display":{"promptText":"After counting all 28 items in a set, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-23-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":32,"b":null,"op":"count","answer":32,"display":{"promptText":"After counting all 32 items in a set, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-23-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":null,"op":"count","answer":36,"display":{"promptText":"After counting all 36 items in a set, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-45-001",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":50,"b":null,"op":"count","answer":50,"display":{"promptText":"After counting all 50 items in a set, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-45-002",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":75,"b":null,"op":"count","answer":75,"display":{"promptText":"After counting all 75 items in a set, what is the cardinality?"}},
  },
  {
    itemId: "counting-conc-cardinality-45-003",
    modeId: "counting",
    itemFamily: "conceptual",
    subskill: "cardinality",
    structureType: "countObjects",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":null,"op":"count","answer":100,"display":{"promptText":"After counting all 100 items in a set, what is the cardinality?"}},
  },
];
