// Auto-generated item data for mode "division". Do not hand-edit; regenerate
// via `npm run bank:split` or `npm run bank:export`.

import { APPROVED } from "../reviewStatus.js";

export const ITEMS = [
  {
    itemId: "division-app-001",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":36,"b":6,"op":"÷","answer":6,"display":{"promptText":"36 apples are shared equally among 6 baskets. How many apples go in each basket?"}},
  },
  {
    itemId: "division-app-002",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":24,"b":4,"op":"÷","answer":6,"display":{"promptText":"24 pencils are split equally into 4 groups. How many pencils are in each group?"}},
  },
  {
    itemId: "division-app-003",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":45,"b":5,"op":"÷","answer":9,"display":{"promptText":"A teacher hands out 45 markers equally to 5 tables. How many markers does each table get?"}},
  },
  {
    itemId: "division-app-004",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":56,"b":8,"op":"÷","answer":7,"display":{"promptText":"56 stickers are packed equally into 8 packets. How many stickers are in each packet?"}},
  },
  {
    itemId: "division-app-005",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":42,"b":7,"op":"÷","answer":6,"display":{"promptText":"42 grapes are placed equally into 7 small bowls. How many grapes are in each bowl?"}},
  },
  {
    itemId: "division-app-006",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":81,"b":9,"op":"÷","answer":9,"display":{"promptText":"81 chairs are arranged in 9 equal rows. How many chairs are in each row?"}},
  },
  {
    itemId: "division-app-007",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":63,"b":9,"op":"÷","answer":7,"display":{"promptText":"A team has 63 cones to share equally among 9 practice groups. How many cones does each group get?"}},
  },
  {
    itemId: "division-app-008",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":48,"b":6,"op":"÷","answer":8,"display":{"promptText":"48 cookies are packed 6 per box. How many boxes are filled?"}},
  },
  {
    itemId: "division-app-009",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":72,"b":8,"op":"÷","answer":9,"display":{"promptText":"A baker uses 72 eggs, 8 eggs per batch. How many batches did the baker make?"}},
  },
  {
    itemId: "division-app-010",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":30,"b":5,"op":"÷","answer":6,"display":{"promptText":"30 stickers are shared equally among 5 friends. How many stickers does each friend get?"}},
  },
  {
    itemId: "division-app-011",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":64,"b":8,"op":"÷","answer":8,"display":{"promptText":"64 beads are placed equally on 8 strings. How many beads are on each string?"}},
  },
  {
    itemId: "division-app-012",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "quotitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":35,"b":5,"op":"÷","answer":7,"display":{"promptText":"35 oranges are packed in bags of 5. How many bags did the store fill?"}},
  },
  {
    itemId: "division-app-013",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":54,"b":6,"op":"÷","answer":9,"display":{"promptText":"A coach splits 54 cones equally among 6 stations. How many cones go to each station?"}},
  },
  {
    itemId: "division-app-014",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":28,"b":4,"op":"÷","answer":7,"display":{"promptText":"28 pears are placed equally into 4 baskets. How many pears go in each basket?"}},
  },
  {
    itemId: "division-app-015",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":2,"op":"÷","answer":3,"display":{"promptText":"6 cookies are shared equally between 2 kids. How many cookies for each kid?"}},
  },
  {
    itemId: "division-app-016",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":2,"op":"÷","answer":4,"display":{"promptText":"8 marbles are split equally into 2 jars. How many marbles in each jar?"}},
  },
  {
    itemId: "division-app-017",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":2,"op":"÷","answer":2,"display":{"promptText":"4 stickers are given equally to 2 friends. How many stickers does each friend get?"}},
  },
  {
    itemId: "division-app-018",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":3,"op":"÷","answer":2,"display":{"promptText":"6 small marbles are arranged into 3 equal groups. How many marbles per group?"}},
  },
  {
    itemId: "division-app-019",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":3,"op":"÷","answer":3,"display":{"promptText":"9 gold stars are placed in 3 rows equally. How many stars per row?"}},
  },
  {
    itemId: "division-app-020",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":5,"op":"÷","answer":2,"display":{"promptText":"10 fish are placed evenly across 5 tanks. How many fish per tank?"}},
  },
  {
    itemId: "division-app-021",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":4,"op":"÷","answer":2,"display":{"promptText":"8 stickers are shared equally by 4 kids. How many stickers per kid?"}},
  },
  {
    itemId: "division-app-022",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":2,"op":"÷","answer":5,"display":{"promptText":"10 cubes are arranged into 2 equal stacks. How many cubes per stack?"}},
  },
  {
    itemId: "division-app-023",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":3,"op":"÷","answer":3,"display":{"promptText":"9 buttons are sorted equally into 3 small jars. How many buttons per jar?"}},
  },
  {
    itemId: "division-app-024",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":12,"b":4,"op":"÷","answer":3,"display":{"promptText":"12 books are split equally onto 4 shelves. How many books per shelf?"}},
  },
  {
    itemId: "division-app-025",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":15,"b":3,"op":"÷","answer":5,"display":{"promptText":"15 cards are dealt equally to 3 players. How many cards does each player get?"}},
  },
  {
    itemId: "division-app-026",
    modeId: "division",
    itemFamily: "application",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":6,"op":"÷","answer":3,"display":{"promptText":"18 cookies are placed on 6 plates equally. How many cookies per plate?"}},
  },
  {
    itemId: "division-app-027",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":24,"b":4,"op":"÷","answer":6,"display":{"promptText":"24 students are split into groups of 4. How many groups are there?"}},
  },
  {
    itemId: "division-app-028",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":5,"op":"÷","answer":7,"display":{"promptText":"35 stickers are shared equally by 5 kids. How many stickers per kid?"}},
  },
  {
    itemId: "division-app-029",
    modeId: "division",
    itemFamily: "application",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":6,"op":"÷","answer":6,"display":{"promptText":"36 marbles are sorted equally into 6 jars. How many marbles per jar?"}},
  },
  {
    itemId: "division-app-030",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":20,"b":5,"op":"÷","answer":4,"display":{"promptText":"20 books are placed on 5 shelves equally. How many books per shelf?"}},
  },
  {
    itemId: "division-app-031",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":24,"b":8,"op":"÷","answer":3,"display":{"promptText":"24 children are split into 8 small teams equally. How many per team?"}},
  },
  {
    itemId: "division-app-032",
    modeId: "division",
    itemFamily: "application",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":6,"op":"÷","answer":5,"display":{"promptText":"30 candies are placed equally in 6 bags. How many candies per bag?"}},
  },
  {
    itemId: "division-proc-partitioning-K1-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":2,"op":"÷","answer":3,"display":{"promptText":"6 ÷ 2 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-K1-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":2,"op":"÷","answer":4,"display":{"promptText":"8 ÷ 2 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-K1-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":2,"op":"÷","answer":2,"display":{"promptText":"4 ÷ 2 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-23-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":12,"b":4,"op":"÷","answer":3,"display":{"promptText":"12 ÷ 4 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-23-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":15,"b":3,"op":"÷","answer":5,"display":{"promptText":"15 ÷ 3 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-23-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":6,"op":"÷","answer":3,"display":{"promptText":"18 ÷ 6 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-45-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":48,"b":6,"op":"÷","answer":8,"display":{"promptText":"48 ÷ 6 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-45-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":56,"b":7,"op":"÷","answer":8,"display":{"promptText":"56 ÷ 7 = ?"}},
  },
  {
    itemId: "division-proc-partitioning-45-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":81,"b":9,"op":"÷","answer":9,"display":{"promptText":"81 ÷ 9 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-K1-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":3,"op":"÷","answer":2,"display":{"promptText":"6 ÷ 3 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-K1-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":3,"op":"÷","answer":3,"display":{"promptText":"9 ÷ 3 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-K1-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":5,"op":"÷","answer":2,"display":{"promptText":"10 ÷ 5 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-23-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":24,"b":4,"op":"÷","answer":6,"display":{"promptText":"24 ÷ 4 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-23-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":5,"op":"÷","answer":7,"display":{"promptText":"35 ÷ 5 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-23-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":6,"op":"÷","answer":6,"display":{"promptText":"36 ÷ 6 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-45-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":72,"b":9,"op":"÷","answer":8,"display":{"promptText":"72 ÷ 9 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-45-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":64,"b":8,"op":"÷","answer":8,"display":{"promptText":"64 ÷ 8 = ?"}},
  },
  {
    itemId: "division-proc-inverseFact-45-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":49,"b":7,"op":"÷","answer":7,"display":{"promptText":"49 ÷ 7 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-K1-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":4,"op":"÷","answer":2,"display":{"promptText":"8 ÷ 4 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-K1-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":2,"op":"÷","answer":5,"display":{"promptText":"10 ÷ 2 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-K1-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":6,"op":"÷","answer":2,"display":{"promptText":"12 ÷ 6 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-23-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":20,"b":5,"op":"÷","answer":4,"display":{"promptText":"20 ÷ 5 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-23-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":24,"b":8,"op":"÷","answer":3,"display":{"promptText":"24 ÷ 8 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-23-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":6,"op":"÷","answer":5,"display":{"promptText":"30 ÷ 6 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-45-001",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":144,"b":12,"op":"÷","answer":12,"display":{"promptText":"144 ÷ 12 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-45-002",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":4,"op":"÷","answer":25,"display":{"promptText":"100 ÷ 4 = ?"}},
  },
  {
    itemId: "division-proc-unknownQuotient-45-003",
    modeId: "division",
    itemFamily: "procedural",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":132,"b":11,"op":"÷","answer":12,"display":{"promptText":"132 ÷ 11 = ?"}},
  },
  {
    itemId: "division-conc-partitioning-K1-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":2,"op":"÷","answer":3,"display":{"promptText":"Share 6 fairly among 2: how many for each?"}},
  },
  {
    itemId: "division-conc-partitioning-K1-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":2,"op":"÷","answer":4,"display":{"promptText":"How many in each group when 8 is split into 2 equal groups?"}},
  },
  {
    itemId: "division-conc-partitioning-K1-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":4,"b":2,"op":"÷","answer":2,"display":{"promptText":"Divide 4 into 2 equal parts. Each part is?"}},
  },
  {
    itemId: "division-conc-partitioning-23-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":12,"b":4,"op":"÷","answer":3,"display":{"promptText":"Split 12 into 4 equal groups. Each group has?"}},
  },
  {
    itemId: "division-conc-partitioning-23-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":15,"b":3,"op":"÷","answer":5,"display":{"promptText":"Share 15 fairly among 3 friends. Each friend gets?"}},
  },
  {
    itemId: "division-conc-partitioning-23-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":18,"b":6,"op":"÷","answer":3,"display":{"promptText":"Divide 18 evenly into 6 piles. Each pile is?"}},
  },
  {
    itemId: "division-conc-partitioning-45-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":48,"b":6,"op":"÷","answer":8,"display":{"promptText":"Split 48 into 6 equal groups. What is the size of each group?"}},
  },
  {
    itemId: "division-conc-partitioning-45-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":56,"b":7,"op":"÷","answer":8,"display":{"promptText":"Distribute 56 evenly across 7 boxes. How many per box?"}},
  },
  {
    itemId: "division-conc-partitioning-45-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "partitioning",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":81,"b":9,"op":"÷","answer":9,"display":{"promptText":"Share 81 fairly among 9 friends. Each friend gets?"}},
  },
  {
    itemId: "division-conc-inverseFact-K1-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":6,"b":3,"op":"÷","answer":2,"display":{"promptText":"If 2 × 3 = 6, then 6 ÷ 3 equals?"}},
  },
  {
    itemId: "division-conc-inverseFact-K1-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":9,"b":3,"op":"÷","answer":3,"display":{"promptText":"9 ÷ 3 = ? Think: 3 times what makes 9?"}},
  },
  {
    itemId: "division-conc-inverseFact-K1-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":5,"op":"÷","answer":2,"display":{"promptText":"Since 5 × 2 = 10, what is 10 ÷ 5?"}},
  },
  {
    itemId: "division-conc-inverseFact-23-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":24,"b":4,"op":"÷","answer":6,"display":{"promptText":"If 4 × 6 = 24, what is 24 ÷ 4?"}},
  },
  {
    itemId: "division-conc-inverseFact-23-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":5,"op":"÷","answer":7,"display":{"promptText":"35 ÷ 5 = ? Think: 5 times what makes 35?"}},
  },
  {
    itemId: "division-conc-inverseFact-23-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":6,"op":"÷","answer":6,"display":{"promptText":"Since 6 × 6 = 36, what is 36 ÷ 6?"}},
  },
  {
    itemId: "division-conc-inverseFact-45-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":72,"b":9,"op":"÷","answer":8,"display":{"promptText":"If 9 × 8 = 72, then 72 ÷ 9 equals?"}},
  },
  {
    itemId: "division-conc-inverseFact-45-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":64,"b":8,"op":"÷","answer":8,"display":{"promptText":"64 ÷ 8 = ? Think: 8 times what makes 64?"}},
  },
  {
    itemId: "division-conc-inverseFact-45-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "inverseFact",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":49,"b":7,"op":"÷","answer":7,"display":{"promptText":"Since 7 × 7 = 49, what is 49 ÷ 7?"}},
  },
  {
    itemId: "division-conc-unknownQuotient-K1-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":8,"b":4,"op":"÷","answer":2,"display":{"promptText":"Find the quotient: 8 ÷ 4"}},
  },
  {
    itemId: "division-conc-unknownQuotient-K1-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":10,"b":2,"op":"÷","answer":5,"display":{"promptText":"What number is 10 ÷ 2?"}},
  },
  {
    itemId: "division-conc-unknownQuotient-K1-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":6,"op":"÷","answer":2,"display":{"promptText":"Find the quotient of 12 and 6."}},
  },
  {
    itemId: "division-conc-unknownQuotient-23-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":20,"b":5,"op":"÷","answer":4,"display":{"promptText":"Find the quotient: 20 ÷ 5"}},
  },
  {
    itemId: "division-conc-unknownQuotient-23-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":24,"b":8,"op":"÷","answer":3,"display":{"promptText":"What number is 24 ÷ 8?"}},
  },
  {
    itemId: "division-conc-unknownQuotient-23-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":30,"b":6,"op":"÷","answer":5,"display":{"promptText":"Find the quotient of 30 and 6."}},
  },
  {
    itemId: "division-conc-unknownQuotient-45-001",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":144,"b":12,"op":"÷","answer":12,"display":{"promptText":"Find the quotient: 144 ÷ 12"}},
  },
  {
    itemId: "division-conc-unknownQuotient-45-002",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":100,"b":4,"op":"÷","answer":25,"display":{"promptText":"What number is 100 ÷ 4?"}},
  },
  {
    itemId: "division-conc-unknownQuotient-45-003",
    modeId: "division",
    itemFamily: "conceptual",
    subskill: "unknownQuotient",
    structureType: "partitiveDivision",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":132,"b":11,"op":"÷","answer":12,"display":{"promptText":"Find the quotient of 132 and 11."}},
  },
];
