// Auto-generated item data for mode "placeValue". Do not hand-edit; regenerate
// via `npm run bank:split` or `npm run bank:export`.

import { APPROVED } from "../reviewStatus.js";

export const ITEMS = [
  {
    itemId: "placevalue-app-001",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":64,"b":null,"op":"place","answer":64,"display":{"ones":4,"tens":6,"type":"build","number":64,"promptText":"A class builds a number with 6 tens and 4 ones. What number did they build?"}},
  },
  {
    itemId: "placevalue-app-002",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":128,"b":null,"op":"place","answer":128,"display":{"ones":8,"tens":12,"type":"build","number":128,"promptText":"A puzzle card shows 12 tens and 8 ones. What number is shown?"}},
  },
  {
    itemId: "placevalue-app-003",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":305,"b":null,"op":"place","answer":305,"display":{"ones":5,"tens":30,"type":"build","number":305,"promptText":"A team records 30 tens and 5 ones. What number do those blocks make?"}},
  },
  {
    itemId: "placevalue-app-004",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":92,"b":null,"op":"place","answer":92,"display":{"ones":2,"tens":9,"type":"build","number":92,"promptText":"A storage bin holds 9 tens of beads and 2 extra beads. How many beads in all?"}},
  },
  {
    itemId: "placevalue-app-005",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":240,"b":null,"op":"place","answer":240,"display":{"ones":0,"tens":24,"type":"build","number":240,"promptText":"A stack has 24 tens and 0 ones. What number does the stack show?"}},
  },
  {
    itemId: "placevalue-app-006",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":47,"b":null,"op":"place","answer":47,"display":{"ones":7,"tens":4,"type":"build","number":47,"promptText":"A box has 4 tens of crayons and 7 extra crayons. How many crayons are in the box?"}},
  },
  {
    itemId: "placevalue-app-007",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":156,"b":null,"op":"place","answer":156,"display":{"ones":6,"tens":15,"type":"build","number":156,"promptText":"A model uses 15 tens of blocks and 6 ones. What number do the blocks show?"}},
  },
  {
    itemId: "placevalue-app-008",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":503,"b":null,"op":"place","answer":503,"display":{"ones":3,"tens":50,"type":"build","number":503,"promptText":"A counter shows 50 tens and 3 ones. What number is on the counter?"}},
  },
  {
    itemId: "placevalue-app-009",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":80,"b":null,"op":"place","answer":80,"display":{"ones":0,"tens":8,"type":"build","number":80,"promptText":"A pencil case organizes pencils as 8 tens and 0 ones. How many pencils in all?"}},
  },
  {
    itemId: "placevalue-app-010",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":213,"b":null,"op":"place","answer":213,"display":{"ones":3,"tens":21,"type":"build","number":213,"promptText":"A garden tracks 21 tens of seeds and 3 ones. How many seeds were tracked?"}},
  },
  {
    itemId: "placevalue-app-011",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":408,"b":null,"op":"place","answer":408,"display":{"ones":8,"tens":40,"type":"build","number":408,"promptText":"A scoreboard reads 40 tens and 8 ones. What number does the scoreboard show?"}},
  },
  {
    itemId: "placevalue-app-012",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":75,"b":null,"op":"place","answer":75,"display":{"ones":5,"tens":7,"type":"build","number":75,"promptText":"A library bin shows 7 tens of cards and 5 ones. How many cards are in the bin?"}},
  },
  {
    itemId: "placevalue-app-013",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":null,"op":"place","answer":1,"display":{"ones":2,"tens":1,"type":"tens_in","number":12,"promptText":"How many tens are in 12?"}},
  },
  {
    itemId: "placevalue-app-014",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":15,"b":null,"op":"place","answer":1,"display":{"ones":5,"tens":1,"type":"tens_in","number":15,"promptText":"How many tens are in 15?"}},
  },
  {
    itemId: "placevalue-app-015",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":null,"op":"place","answer":2,"display":{"ones":2,"tens":1,"type":"ones_in","number":12,"promptText":"How many ones are in 12?"}},
  },
  {
    itemId: "placevalue-app-016",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":47,"b":null,"op":"place","answer":4,"display":{"ones":7,"tens":4,"type":"tens_in","number":47,"promptText":"How many tens are in 47?"}},
  },
  {
    itemId: "placevalue-app-017",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":53,"b":null,"op":"place","answer":5,"display":{"ones":3,"tens":5,"type":"tens_in","number":53,"promptText":"How many tens are in 53?"}},
  },
  {
    itemId: "placevalue-app-018",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":null,"op":"place","answer":6,"display":{"ones":6,"tens":3,"type":"ones_in","number":36,"promptText":"How many ones are in 36?"}},
  },
  {
    itemId: "placevalue-app-019",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":23,"display":{"ones":4,"tens":23,"type":"tens_in","number":234,"promptText":"How many total tens are in 234?"}},
  },
  {
    itemId: "placevalue-app-020",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":58,"display":{"ones":0,"tens":58,"type":"tens_in","number":580,"promptText":"How many total tens are in 580?"}},
  },
  {
    itemId: "placevalue-app-021",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":4,"display":{"ones":4,"tens":37,"type":"ones_in","number":374,"promptText":"How many ones are in 374?"}},
  },
  {
    itemId: "placevalue-app-022",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":13,"b":null,"op":"place","answer":13,"display":{"ones":3,"tens":1,"type":"build","number":13,"promptText":"A counter shows 1 ten and 3 ones. What number is on the counter?"}},
  },
  {
    itemId: "placevalue-app-023",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":20,"b":null,"op":"place","answer":20,"display":{"ones":0,"tens":2,"type":"build","number":20,"promptText":"A pile has 2 tens and 0 ones of cubes. How many cubes in the pile?"}},
  },
  {
    itemId: "placevalue-app-024",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":17,"b":null,"op":"place","answer":17,"display":{"ones":7,"tens":1,"type":"build","number":17,"promptText":"A bin shows 1 ten and 7 ones of marbles. How many marbles in the bin?"}},
  },
  {
    itemId: "placevalue-app-025",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":58,"b":null,"op":"place","answer":58,"display":{"ones":8,"tens":5,"type":"build","number":58,"promptText":"A scoreboard shows 5 tens and 8 ones. What number is on the scoreboard?"}},
  },
  {
    itemId: "placevalue-app-026",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":72,"b":null,"op":"place","answer":72,"display":{"ones":2,"tens":7,"type":"build","number":72,"promptText":"A bin holds 7 tens and 2 ones of cards. How many cards in the bin?"}},
  },
  {
    itemId: "placevalue-app-027",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":49,"b":null,"op":"place","answer":49,"display":{"ones":9,"tens":4,"type":"build","number":49,"promptText":"A row shows 4 tens and 9 ones of stickers. How many stickers in the row?"}},
  },
  {
    itemId: "placevalue-app-028",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":234,"display":{"ones":4,"tens":23,"type":"build","number":234,"promptText":"A counter shows 23 tens and 4 ones. What number is on the counter?"}},
  },
  {
    itemId: "placevalue-app-029",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":580,"display":{"ones":0,"tens":58,"type":"build","number":580,"promptText":"A scoreboard reads 58 tens and 0 ones. What number does it show?"}},
  },
  {
    itemId: "placevalue-app-030",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":374,"display":{"ones":4,"tens":37,"type":"build","number":374,"promptText":"A row shows 37 tens and 4 ones of beads. How many beads in the row?"}},
  },
  {
    itemId: "placevalue-app-031",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":14,"b":null,"op":"place","answer":14,"display":{"ones":4,"tens":1,"type":"build","number":14,"promptText":"A bag has 10 candies plus 4 more. How many candies in total?"}},
  },
  {
    itemId: "placevalue-app-032",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"place","answer":18,"display":{"ones":8,"tens":1,"type":"build","number":18,"promptText":"A counter has 10 marks plus 8 more. How many marks in total?"}},
  },
  {
    itemId: "placevalue-app-033",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":25,"b":null,"op":"place","answer":25,"display":{"ones":5,"tens":2,"type":"build","number":25,"promptText":"A row shows 20 cards plus 5 more. How many cards in total?"}},
  },
  {
    itemId: "placevalue-app-034",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"place","answer":35,"display":{"ones":5,"tens":3,"type":"build","number":35,"promptText":"A pencil case has 30 pencils plus 5 more. How many pencils in total?"}},
  },
  {
    itemId: "placevalue-app-035",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":63,"b":null,"op":"place","answer":63,"display":{"ones":3,"tens":6,"type":"build","number":63,"promptText":"A bowl shows 60 grapes plus 3 more. How many grapes in total?"}},
  },
  {
    itemId: "placevalue-app-036",
    modeId: "placeValue",
    itemFamily: "application",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":87,"b":null,"op":"place","answer":87,"display":{"ones":7,"tens":8,"type":"build","number":87,"promptText":"A puzzle uses 80 pieces plus 7 more. How many pieces in total?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-23-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":58,"b":null,"op":"place","answer":58,"display":{"ones":8,"tens":5,"type":"build","number":58,"promptText":"What number equals 5 tens + 8 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-23-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":72,"b":null,"op":"place","answer":72,"display":{"ones":2,"tens":7,"type":"build","number":72,"promptText":"What number equals 7 tens + 2 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-23-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":49,"b":null,"op":"place","answer":49,"display":{"ones":9,"tens":4,"type":"build","number":49,"promptText":"What number equals 4 tens + 9 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-45-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":234,"display":{"ones":4,"tens":23,"type":"build","number":234,"promptText":"What number equals 23 tens + 4 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-45-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":580,"display":{"ones":0,"tens":58,"type":"build","number":580,"promptText":"What number equals 58 tens + 0 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-45-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":374,"display":{"ones":4,"tens":37,"type":"build","number":374,"promptText":"What number equals 37 tens + 4 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-K1-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":13,"b":null,"op":"place","answer":13,"display":{"ones":3,"tens":1,"type":"build","number":13,"promptText":"What number equals 1 ten + 3 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-K1-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":20,"b":null,"op":"place","answer":20,"display":{"ones":0,"tens":2,"type":"build","number":20,"promptText":"What number equals 2 tens + 0 ones?"}},
  },
  {
    itemId: "placevalue-conc-expandedForm-K1-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":17,"b":null,"op":"place","answer":17,"display":{"ones":7,"tens":1,"type":"build","number":17,"promptText":"What number equals 1 ten + 7 ones?"}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-23-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"place","answer":35,"display":{"ones":5,"tens":3,"type":"build","number":35,"promptText":"Regroup 30 + 5 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-23-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":63,"b":null,"op":"place","answer":63,"display":{"ones":3,"tens":6,"type":"build","number":63,"promptText":"Regroup 60 + 3 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-23-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":87,"b":null,"op":"place","answer":87,"display":{"ones":7,"tens":8,"type":"build","number":87,"promptText":"Regroup 80 + 7 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-45-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":234,"display":{"ones":4,"tens":23,"type":"build","number":234,"promptText":"Regroup 200 + 30 + 4 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-45-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":580,"display":{"ones":0,"tens":58,"type":"build","number":580,"promptText":"Regroup 500 + 80 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-45-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":374,"display":{"ones":4,"tens":37,"type":"build","number":374,"promptText":"Regroup 300 + 70 + 4 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-K1-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":14,"b":null,"op":"place","answer":14,"display":{"ones":4,"tens":1,"type":"build","number":14,"promptText":"Regroup 10 + 4 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-K1-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"place","answer":18,"display":{"ones":8,"tens":1,"type":"build","number":18,"promptText":"Regroup 10 + 8 to a single number."}},
  },
  {
    itemId: "placevalue-conc-regroupingSense-K1-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":25,"b":null,"op":"place","answer":25,"display":{"ones":5,"tens":2,"type":"build","number":25,"promptText":"Regroup 20 + 5 to a single number."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-23-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":47,"b":null,"op":"place","answer":4,"display":{"ones":7,"tens":4,"type":"tens_in","number":47,"promptText":"Identify the tens digit of 47."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-23-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":53,"b":null,"op":"place","answer":5,"display":{"ones":3,"tens":5,"type":"tens_in","number":53,"promptText":"Identify the tens digit of 53."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-23-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":null,"op":"place","answer":6,"display":{"ones":6,"tens":3,"type":"ones_in","number":36,"promptText":"Identify the ones digit of 36."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-45-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":23,"display":{"ones":4,"tens":23,"type":"tens_in","number":234,"promptText":"Determine the total tens in 234."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-45-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":58,"display":{"ones":0,"tens":58,"type":"tens_in","number":580,"promptText":"Determine the total tens in 580."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-45-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":4,"display":{"ones":4,"tens":37,"type":"ones_in","number":374,"promptText":"Determine the units digit of 374."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-K1-001",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":null,"op":"place","answer":1,"display":{"ones":2,"tens":1,"type":"tens_in","number":12,"promptText":"Identify the tens digit of 12."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-K1-002",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":15,"b":null,"op":"place","answer":1,"display":{"ones":5,"tens":1,"type":"tens_in","number":15,"promptText":"Identify the tens digit of 15."}},
  },
  {
    itemId: "placevalue-conc-tensOnes-K1-003",
    modeId: "placeValue",
    itemFamily: "conceptual",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":null,"op":"place","answer":2,"display":{"ones":2,"tens":1,"type":"ones_in","number":12,"promptText":"Identify the ones digit of 12."}},
  },
  {
    itemId: "placevalue-proc-expandedForm-23-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":58,"b":null,"op":"place","answer":58,"display":{"ones":8,"tens":5,"type":"build","number":58,"promptText":"5 tens + 8 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-23-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":72,"b":null,"op":"place","answer":72,"display":{"ones":2,"tens":7,"type":"build","number":72,"promptText":"7 tens + 2 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-23-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":49,"b":null,"op":"place","answer":49,"display":{"ones":9,"tens":4,"type":"build","number":49,"promptText":"4 tens + 9 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-45-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":234,"display":{"ones":4,"tens":23,"type":"build","number":234,"promptText":"23 tens + 4 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-45-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":580,"display":{"ones":0,"tens":58,"type":"build","number":580,"promptText":"58 tens + 0 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-45-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":374,"display":{"ones":4,"tens":37,"type":"build","number":374,"promptText":"37 tens + 4 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-K1-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":13,"b":null,"op":"place","answer":13,"display":{"ones":3,"tens":1,"type":"build","number":13,"promptText":"1 ten + 3 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-K1-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":20,"b":null,"op":"place","answer":20,"display":{"ones":0,"tens":2,"type":"build","number":20,"promptText":"2 tens + 0 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-expandedForm-K1-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "expandedForm",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":17,"b":null,"op":"place","answer":17,"display":{"ones":7,"tens":1,"type":"build","number":17,"promptText":"1 ten + 7 ones = ?"}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-23-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":35,"b":null,"op":"place","answer":35,"display":{"ones":5,"tens":3,"type":"build","number":35,"promptText":"Combine 3 tens and 5 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-23-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":63,"b":null,"op":"place","answer":63,"display":{"ones":3,"tens":6,"type":"build","number":63,"promptText":"Combine 6 tens and 3 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-23-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":87,"b":null,"op":"place","answer":87,"display":{"ones":7,"tens":8,"type":"build","number":87,"promptText":"Combine 8 tens and 7 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-45-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":234,"display":{"ones":4,"tens":23,"type":"build","number":234,"promptText":"Combine 23 tens and 4 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-45-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":580,"display":{"ones":0,"tens":58,"type":"build","number":580,"promptText":"Combine 58 tens and 0 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-45-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":374,"display":{"ones":4,"tens":37,"type":"build","number":374,"promptText":"Combine 37 tens and 4 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-K1-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":14,"b":null,"op":"place","answer":14,"display":{"ones":4,"tens":1,"type":"build","number":14,"promptText":"Combine 1 ten and 4 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-K1-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":18,"b":null,"op":"place","answer":18,"display":{"ones":8,"tens":1,"type":"build","number":18,"promptText":"Combine 1 ten and 8 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-regroupingSense-K1-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "regroupingSense",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":25,"b":null,"op":"place","answer":25,"display":{"ones":5,"tens":2,"type":"build","number":25,"promptText":"Combine 2 tens and 5 ones into one number."}},
  },
  {
    itemId: "placevalue-proc-tensOnes-23-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":47,"b":null,"op":"place","answer":4,"display":{"ones":7,"tens":4,"type":"tens_in","number":47,"promptText":"How many tens in 47?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-23-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":53,"b":null,"op":"place","answer":5,"display":{"ones":3,"tens":5,"type":"tens_in","number":53,"promptText":"How many tens in 53?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-23-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":36,"b":null,"op":"place","answer":6,"display":{"ones":6,"tens":3,"type":"ones_in","number":36,"promptText":"How many ones in 36?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-45-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":234,"b":null,"op":"place","answer":23,"display":{"ones":4,"tens":23,"type":"tens_in","number":234,"promptText":"How many tens in 234?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-45-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":580,"b":null,"op":"place","answer":58,"display":{"ones":0,"tens":58,"type":"tens_in","number":580,"promptText":"How many tens in 580?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-45-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":374,"b":null,"op":"place","answer":4,"display":{"ones":4,"tens":37,"type":"ones_in","number":374,"promptText":"How many ones in 374?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-K1-001",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":null,"op":"place","answer":1,"display":{"ones":2,"tens":1,"type":"tens_in","number":12,"promptText":"How many tens in 12?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-K1-002",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":15,"b":null,"op":"place","answer":1,"display":{"ones":5,"tens":1,"type":"tens_in","number":15,"promptText":"How many tens in 15?"}},
  },
  {
    itemId: "placevalue-proc-tensOnes-K1-003",
    modeId: "placeValue",
    itemFamily: "procedural",
    subskill: "tensOnes",
    structureType: "buildFromUnits",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":12,"b":null,"op":"place","answer":2,"display":{"ones":2,"tens":1,"type":"ones_in","number":12,"promptText":"How many ones in 12?"}},
  },
];
