// Auto-generated item data for mode "skipCounting". Do not hand-edit; regenerate
// via `npm run bank:split` or `npm run bank:export`.

import { APPROVED } from "../reviewStatus.js";

export const ITEMS = [
  {
    itemId: "skipcounting-app-001",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":21,"display":{"step":3,"sequence":[12,15,18],"promptText":"Count by 3s: 12, 15, 18. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-002",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"Count by 6s: 6, 12, 18. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-003",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"step":4,"sequence":[32,36,40],"promptText":"Count by 4s: 32, 36, 40. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-004",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":80,"display":{"step":10,"sequence":[50,60,70],"promptText":"Count by 10s: 50, 60, 70. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-005",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"step":5,"sequence":[45,50,55],"promptText":"Count by 5s: 45, 50, 55. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-006",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":90,"display":{"step":5,"sequence":[75,80,85],"promptText":"A class earns 5 stars per chapter: 75, 80, 85. How many stars after one more chapter?"}},
  },
  {
    itemId: "skipcounting-app-007",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"step":4,"sequence":[16,20,24],"promptText":"Count by 4s: 16, 20, 24. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-008",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"step":4,"sequence":[18,22,26],"promptText":"Count by 4s: 18, 22, 26. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-009",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"step":6,"sequence":[12,18,24],"promptText":"A team adds 6 points each round: 12, 18, 24. How many points after one more round?"}},
  },
  {
    itemId: "skipcounting-app-010",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":14,"display":{"step":4,"sequence":[2,6,10],"promptText":"Count by 4s: 2, 6, 10. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-011",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":50,"display":{"step":10,"sequence":[20,30,40],"promptText":"Count by 10s: 20, 30, 40. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-012",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":35,"display":{"step":7,"sequence":[14,21,28],"promptText":"Count by 7s: 14, 21, 28. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-013",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":36,"display":{"step":9,"sequence":[9,18,27],"promptText":"Count by 9s: 9, 18, 27. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-014",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"step":2,"sequence":[2,4,6],"promptText":"Count by 2s: 2, 4, 6. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-015",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"step":5,"sequence":[5,10,15],"promptText":"Count by 5s: 5, 10, 15. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-016",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":6,"display":{"step":2,"sequence":[0,2,4],"promptText":"Count by 2s: 0, 2, 4. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-017",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"step":3,"sequence":[3,6,9],"promptText":"Count by 3s: 3, 6, 9. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-018",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":9,"display":{"step":2,"sequence":[1,3,5,7],"promptText":"Count by 2s: 1, 3, 5, 7. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-019",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"step":4,"sequence":[4,8,12],"promptText":"Count by 4s: 4, 8, 12. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-020",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":15,"display":{"step":5,"sequence":[5,10],"promptText":"5 marbles per jar; after 1, 2 jars: 5, 10. After 3 jars?","promptOptions":["A jar holds 5 marbles. 1 jar: 5, 2 jars: 10. How many marbles in 3 jars?","Marbles: 1 jar (5), 2 jars (10). How many marbles in 3 jars?"]}},
  },
  {
    itemId: "skipcounting-app-021",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"step":3,"sequence":[3,6,9],"promptText":"3 cookies per plate; after 1, 2, 3 plates: 3, 6, 9. After 4 plates?","promptOptions":["Each plate has 3 cookies. 1 plate: 3, 2 plates: 6, 3 plates: 9. How many on 4 plates?","A baker puts 3 cookies on each plate: 1 (3), 2 (6), 3 (9). How many total on 4 plates?"]}},
  },
  {
    itemId: "skipcounting-app-022",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"step":2,"sequence":[2,4,6],"promptText":"2 wheels per scooter; after 1, 2, 3 scooters: 2, 4, 6. After 4 scooters?","promptOptions":["Each scooter has 2 wheels. 1 scooter: 2, 2 scooters: 4, 3 scooters: 6. How many on 4?","A scooter has 2 wheels: 1 (2), 2 (4), 3 (6). How many wheels on 4 scooters?"]}},
  },
  {
    itemId: "skipcounting-app-023",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":40,"display":{"step":10,"sequence":[10,20,30],"promptText":"Count by 10s: 10, 20, 30. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-024",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"Counters jump by 6: 6, 12, 18. What's next?"}},
  },
  {
    itemId: "skipcounting-app-025",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"step":11,"sequence":[11,22,33],"promptText":"Count by 11s: 11, 22, 33. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-026",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"step":7,"sequence":[7,14,21],"promptText":"Count by 7s: 7, 14, 21. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-027",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":32,"display":{"step":8,"sequence":[8,16,24],"promptText":"Counting in order 8, 16, 24. What's next?"}},
  },
  {
    itemId: "skipcounting-app-028",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"step":15,"sequence":[15,30,45],"promptText":"Count by 15s: 15, 30, 45. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-029",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"step":4,"sequence":[4,8,12],"promptText":"4 books per shelf; 4, 8, 12 after 3 shelves. After 4 shelves?","promptOptions":["Jayden puts 4 books on each shelf. After 3 shelves he has 4, 8, 12 books. How many books after 4 shelves?","Counting by 4s for each shelf: 4, 8, 12. What comes next?"]}},
  },
  {
    itemId: "skipcounting-app-030",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"6 candies per jar; 6, 12, 18 after 3 jars. After 4 jars?","promptOptions":["Maria fills jars with 6 candies each. After 3 jars she has 6, 12, 18 candies. How many candies after 4 jars?","Counting by 6s for each jar: 6, 12, 18. What comes next?"]}},
  },
  {
    itemId: "skipcounting-app-031",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"step":5,"sequence":[5,10,15],"promptText":"5 stickers per page; 5, 10, 15 after 3 pages. After 4 pages?","promptOptions":["Jayden puts 5 stickers on each page. After 3 pages he has 5, 10, 15 stickers. How many stickers after 4 pages?","Counting by 5s for each page: 5, 10, 15. What comes next?"]}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-23-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"step":4,"sequence":[4,8,12,16],"promptText":"Use skip-counting by 4s for 5 groups of 4."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-23-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"step":5,"sequence":[5,10,15,20,25],"promptText":"Use skip-counting by 5s for 6 groups of 5."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-23-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"Use skip-counting by 6s for 4 groups of 6."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-45-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"step":12,"sequence":[12,24,36],"promptText":"Use skip-counting by 12s for 4 groups of 12."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-45-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"step":25,"sequence":[25,50,75],"promptText":"Use skip-counting by 25s for 4 groups of 25."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-45-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":54,"display":{"step":9,"sequence":[9,18,27,36,45],"promptText":"Use skip-counting by 9s for 6 groups of 9."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-K1-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":15,"display":{"step":5,"sequence":[5,10],"promptText":"Use skip-counting by 5s to find 3 groups of 5."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-K1-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"step":3,"sequence":[3,6,9],"promptText":"Use skip-counting by 3s for 4 groups of 3."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-K1-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":10,"display":{"step":2,"sequence":[2,4,6,8],"promptText":"Use skip-counting by 2s for 5 groups of 2."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-23-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":40,"display":{"step":10,"sequence":[10,20,30],"promptText":"Identify the rule in 10, 20, 30 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-23-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"What pattern do 6, 12, 18 follow? Continue it."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-23-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"step":11,"sequence":[11,22,33],"promptText":"Skip-count by 11s: 11, 22, 33, __. What number fills the blank?"}},
  },
  {
    itemId: "skipcounting-conc-patternRule-45-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"step":25,"sequence":[25,50,75],"promptText":"Identify the rule in 25, 50, 75 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-45-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"step":12,"sequence":[12,24,36],"promptText":"What pattern do 12, 24, 36 follow? Continue it."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-45-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":400,"display":{"step":100,"sequence":[100,200,300],"promptText":"Count by 100s: 100, 200, 300. What number comes next?"}},
  },
  {
    itemId: "skipcounting-conc-patternRule-K1-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"step":2,"sequence":[2,4,6],"promptText":"Identify the rule in 2, 4, 6 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-K1-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"step":5,"sequence":[5,10,15],"promptText":"What pattern do 5, 10, 15 follow? Find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-K1-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":6,"display":{"step":2,"sequence":[0,2,4],"promptText":"Recognize the rule in 0, 2, 4 and continue the pattern."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-23-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"step":7,"sequence":[7,14,21],"promptText":"What is the step in 7, 14, 21? Use it to find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-23-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":32,"display":{"step":8,"sequence":[8,16,24],"promptText":"Count by 8s: 8, 16, 24. What number comes next?"}},
  },
  {
    itemId: "skipcounting-conc-stepInference-23-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"step":15,"sequence":[15,30,45],"promptText":"Identify the step for 15, 30, 45 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-45-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":80,"display":{"step":10,"sequence":[50,60,70],"promptText":"What is the step in 50, 60, 70? Use it to find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-45-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":140,"display":{"step":20,"sequence":[80,100,120],"promptText":"Count by 20s: 80, 100, 120. What number comes next?"}},
  },
  {
    itemId: "skipcounting-conc-stepInference-45-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":800,"display":{"step":200,"sequence":[200,400,600],"promptText":"Identify the step for 200, 400, 600 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-K1-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"step":3,"sequence":[3,6,9],"promptText":"What is the step in 3, 6, 9? Use it to find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-K1-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":9,"display":{"step":2,"sequence":[1,3,5,7],"promptText":"Skip-count by 2s: 1, 3, 5, 7, __. What number fills the blank?"}},
  },
  {
    itemId: "skipcounting-conc-stepInference-K1-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"step":4,"sequence":[4,8,12],"promptText":"Identify the step for 4, 8, 12 and the next term."}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-23-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"step":4,"sequence":[4,8,12,16],"promptText":"5 groups of 4: 4, 8, 12, 16, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-23-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"step":5,"sequence":[5,10,15,20,25],"promptText":"6 groups of 5: 5, 10, 15, 20, 25, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-23-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"4 groups of 6: 6, 12, 18, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-45-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"step":12,"sequence":[12,24,36],"promptText":"4 groups of 12: 12, 24, 36, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-45-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"step":25,"sequence":[25,50,75],"promptText":"4 groups of 25: 25, 50, 75, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-45-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":54,"display":{"step":9,"sequence":[9,18,27,36,45],"promptText":"6 groups of 9: 9, 18, 27, 36, 45, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-K1-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":15,"display":{"step":5,"sequence":[5,10],"promptText":"3 groups of 5: 5, 10, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-K1-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"step":3,"sequence":[3,6,9],"promptText":"4 groups of 3: 3, 6, 9, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-K1-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":10,"display":{"step":2,"sequence":[2,4,6,8],"promptText":"5 groups of 2: 2, 4, 6, 8, ?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-23-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":40,"display":{"step":10,"sequence":[10,20,30],"promptText":"Skip count by 10: 10, 20, 30. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-23-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"step":6,"sequence":[6,12,18],"promptText":"Skip count by 6: 6, 12, 18. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-23-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"step":11,"sequence":[11,22,33],"promptText":"Skip count by 11: 11, 22, 33. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-45-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"step":25,"sequence":[25,50,75],"promptText":"Skip count by 25: 25, 50, 75. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-45-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"step":12,"sequence":[12,24,36],"promptText":"Skip count by 12: 12, 24, 36. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-45-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":400,"display":{"step":100,"sequence":[100,200,300],"promptText":"Skip count by 100: 100, 200, 300. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-K1-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"step":2,"sequence":[2,4,6],"promptText":"Skip count by 2: 2, 4, 6. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-K1-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"step":5,"sequence":[5,10,15],"promptText":"Skip count by 5: 5, 10, 15. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-K1-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":6,"display":{"step":2,"sequence":[0,2,4],"promptText":"Skip count by 2 starting at 0: 0, 2, 4. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-23-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"step":7,"sequence":[7,14,21],"promptText":"Find the next term: 7, 14, 21, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-23-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":32,"display":{"step":8,"sequence":[8,16,24],"promptText":"Find the next term: 8, 16, 24, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-23-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"step":15,"sequence":[15,30,45],"promptText":"Find the next term: 15, 30, 45, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-45-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":80,"display":{"step":10,"sequence":[50,60,70],"promptText":"Find the next term: 50, 60, 70, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-45-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":140,"display":{"step":20,"sequence":[80,100,120],"promptText":"Find the next term: 80, 100, 120, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-45-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":800,"display":{"step":200,"sequence":[200,400,600],"promptText":"Find the next term: 200, 400, 600, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-K1-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"step":3,"sequence":[3,6,9],"promptText":"Find the next term: 3, 6, 9, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-K1-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":9,"display":{"step":2,"sequence":[1,3,5,7],"promptText":"Find the next term: 1, 3, 5, 7, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-K1-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"step":4,"sequence":[4,8,12],"promptText":"Find the next term: 4, 8, 12, ?"}},
  },
];
