// Auto-generated item data for mode "skipCounting". Do not hand-edit; regenerate
// via `npm run bank:split` or `npm run bank:export`.

import { APPROVED } from "../reviewStatus.js";

export const ITEMS = [
  {
    itemId: "skipcounting-app-001",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":21,"display":{"sequence":[12,15,18],"step":3,"promptText":"A student counts by 3s: 12, 15, 18. What number comes next?"}},
  },
  {
    itemId: "skipcounting-app-002",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"A clock chime rings every 6 minutes: 6, 12, 18. When does it ring next?"}},
  },
  {
    itemId: "skipcounting-app-003",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"sequence":[32,36,40],"step":4,"promptText":"A pattern increases by 4: 32, 36, 40. What comes next?"}},
  },
  {
    itemId: "skipcounting-app-004",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":80,"display":{"sequence":[50,60,70],"step":10,"promptText":"A jar fills 10 marbles at a time: 50, 60, 70. How many marbles next?"}},
  },
  {
    itemId: "skipcounting-app-005",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"sequence":[45,50,55],"step":5,"promptText":"A scoreboard goes up by 5 points: 45, 50, 55. What score is next?"}},
  },
  {
    itemId: "skipcounting-app-006",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":90,"display":{"sequence":[75,80,85],"step":5,"promptText":"A class earns 5 stars per chapter: 75, 80, 85. How many stars after one more chapter?"}},
  },
  {
    itemId: "skipcounting-app-007",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"sequence":[16,20,24],"step":4,"promptText":"A timer beeps every 4 seconds: 16, 20, 24. When does it beep next?"}},
  },
  {
    itemId: "skipcounting-app-008",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"sequence":[18,22,26],"step":4,"promptText":"A line of beads grows by the same amount each step: 18, 22, 26. What comes next?"}},
  },
  {
    itemId: "skipcounting-app-009",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [8,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"sequence":[12,18,24],"step":6,"promptText":"A team adds 6 points each round: 12, 18, 24. How many points after one more round?"}},
  },
  {
    itemId: "skipcounting-app-010",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":14,"display":{"sequence":[2,6,10],"step":4,"promptText":"A toy car gains 4 pegs each step: 2, 6, 10. How many pegs next?"}},
  },
  {
    itemId: "skipcounting-app-011",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":50,"display":{"sequence":[20,30,40],"step":10,"promptText":"A reader logs minutes growing by the same amount: 20, 30, 40. What comes next?"}},
  },
  {
    itemId: "skipcounting-app-012",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":35,"display":{"sequence":[14,21,28],"step":7,"promptText":"A pattern grows by 7 each step: 14, 21, 28. What comes next?"}},
  },
  {
    itemId: "skipcounting-app-013",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [9,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":36,"display":{"sequence":[9,18,27],"step":9,"promptText":"A counter goes up by 9 each step: 9, 18, 27. What comes next?"}},
  },
  {
    itemId: "skipcounting-app-014",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"sequence":[2,4,6],"step":2,"promptText":"A frog hops 2 each step: 2, 4, 6. What's next?"}},
  },
  {
    itemId: "skipcounting-app-015",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"sequence":[5,10,15],"step":5,"promptText":"A bunny hops 5 carrots each leap: 5, 10, 15. What's next?"}},
  },
  {
    itemId: "skipcounting-app-016",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":6,"display":{"sequence":[0,2,4],"step":2,"promptText":"A toy car moves 2 squares each turn: 0, 2, 4. What's next?"}},
  },
  {
    itemId: "skipcounting-app-017",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"sequence":[3,6,9],"step":3,"promptText":"A pattern shows 3, 6, 9. What's next?"}},
  },
  {
    itemId: "skipcounting-app-018",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":9,"display":{"sequence":[1,3,5,7],"step":2,"promptText":"Odd numbers 1, 3, 5, 7. What's next?"}},
  },
  {
    itemId: "skipcounting-app-019",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"sequence":[4,8,12],"step":4,"promptText":"A row counts 4, 8, 12. What's next?"}},
  },
  {
    itemId: "skipcounting-app-020",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":15,"display":{"sequence":[5,10],"step":5,"promptText":"5 marbles per jar; after 1, 2 jars: 5, 10. After 3 jars?"}},
  },
  {
    itemId: "skipcounting-app-021",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"sequence":[3,6,9],"step":3,"promptText":"3 cookies per plate; after 1, 2, 3 plates: 3, 6, 9. After 4 plates?"}},
  },
  {
    itemId: "skipcounting-app-022",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"sequence":[2,4,6],"step":2,"promptText":"2 wheels per scooter; after 1, 2, 3 scooters: 2, 4, 6. After 4 scooters?"}},
  },
  {
    itemId: "skipcounting-app-023",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":40,"display":{"sequence":[10,20,30],"step":10,"promptText":"A truck adds 10 each load: 10, 20, 30. What's next?"}},
  },
  {
    itemId: "skipcounting-app-024",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"Counters jump by 6: 6, 12, 18. What's next?"}},
  },
  {
    itemId: "skipcounting-app-025",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"sequence":[11,22,33],"step":11,"promptText":"Cards stack 11 at a time: 11, 22, 33. What's next?"}},
  },
  {
    itemId: "skipcounting-app-026",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"sequence":[7,14,21],"step":7,"promptText":"A pattern shows 7, 14, 21. What's next?"}},
  },
  {
    itemId: "skipcounting-app-027",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":32,"display":{"sequence":[8,16,24],"step":8,"promptText":"Counting in order 8, 16, 24. What's next?"}},
  },
  {
    itemId: "skipcounting-app-028",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"sequence":[15,30,45],"step":15,"promptText":"Pattern: 15, 30, 45. What's next?"}},
  },
  {
    itemId: "skipcounting-app-029",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"sequence":[4,8,12],"step":4,"promptText":"4 books per shelf; 4, 8, 12 after 3 shelves. After 4 shelves?"}},
  },
  {
    itemId: "skipcounting-app-030",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"6 candies per jar; 6, 12, 18 after 3 jars. After 4 jars?"}},
  },
  {
    itemId: "skipcounting-app-031",
    modeId: "skipCounting",
    itemFamily: "application",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"sequence":[5,10,15],"step":5,"promptText":"5 stickers per page; 5, 10, 15 after 3 pages. After 4 pages?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-K1-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"sequence":[2,4,6],"step":2,"promptText":"Skip count by 2: 2, 4, 6. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-K1-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"sequence":[5,10,15],"step":5,"promptText":"Skip count by 5: 5, 10, 15. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-K1-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":6,"display":{"sequence":[0,2,4],"step":2,"promptText":"Skip count by 2 starting at 0: 0, 2, 4. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-23-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":40,"display":{"sequence":[10,20,30],"step":10,"promptText":"Skip count by 10: 10, 20, 30. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-23-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"Skip count by 6: 6, 12, 18. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-23-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"sequence":[11,22,33],"step":11,"promptText":"Skip count by 11: 11, 22, 33. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-45-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"sequence":[25,50,75],"step":25,"promptText":"Skip count by 25: 25, 50, 75. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-45-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"sequence":[12,24,36],"step":12,"promptText":"Skip count by 12: 12, 24, 36. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-patternRule-45-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":400,"display":{"sequence":[100,200,300],"step":100,"promptText":"Skip count by 100: 100, 200, 300. What's next?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-K1-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"sequence":[3,6,9],"step":3,"promptText":"Find the next term: 3, 6, 9, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-K1-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":9,"display":{"sequence":[1,3,5,7],"step":2,"promptText":"Find the next term: 1, 3, 5, 7, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-K1-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"sequence":[4,8,12],"step":4,"promptText":"Find the next term: 4, 8, 12, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-23-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"sequence":[7,14,21],"step":7,"promptText":"Find the next term: 7, 14, 21, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-23-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":32,"display":{"sequence":[8,16,24],"step":8,"promptText":"Find the next term: 8, 16, 24, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-23-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"sequence":[15,30,45],"step":15,"promptText":"Find the next term: 15, 30, 45, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-45-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":80,"display":{"sequence":[50,60,70],"step":10,"promptText":"Find the next term: 50, 60, 70, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-45-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":140,"display":{"sequence":[80,100,120],"step":20,"promptText":"Find the next term: 80, 100, 120, ?"}},
  },
  {
    itemId: "skipcounting-proc-stepInference-45-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":800,"display":{"sequence":[200,400,600],"step":200,"promptText":"Find the next term: 200, 400, 600, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-K1-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":15,"display":{"sequence":[5,10],"step":5,"promptText":"3 groups of 5: 5, 10, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-K1-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"sequence":[3,6,9],"step":3,"promptText":"4 groups of 3: 3, 6, 9, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-K1-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":10,"display":{"sequence":[2,4,6,8],"step":2,"promptText":"5 groups of 2: 2, 4, 6, 8, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-23-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"sequence":[4,8,12,16],"step":4,"promptText":"5 groups of 4: 4, 8, 12, 16, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-23-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"sequence":[5,10,15,20,25],"step":5,"promptText":"6 groups of 5: 5, 10, 15, 20, 25, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-23-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"4 groups of 6: 6, 12, 18, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-45-001",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"sequence":[12,24,36],"step":12,"promptText":"4 groups of 12: 12, 24, 36, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-45-002",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"sequence":[25,50,75],"step":25,"promptText":"4 groups of 25: 25, 50, 75, ?"}},
  },
  {
    itemId: "skipcounting-proc-groupsToProduct-45-003",
    modeId: "skipCounting",
    itemFamily: "procedural",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":54,"display":{"sequence":[9,18,27,36,45],"step":9,"promptText":"6 groups of 9: 9, 18, 27, 36, 45, ?"}},
  },
  {
    itemId: "skipcounting-conc-patternRule-K1-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":8,"display":{"sequence":[2,4,6],"step":2,"promptText":"Identify the rule in 2, 4, 6 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-K1-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"sequence":[5,10,15],"step":5,"promptText":"What pattern do 5, 10, 15 follow? Find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-K1-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":6,"display":{"sequence":[0,2,4],"step":2,"promptText":"Recognize the rule in 0, 2, 4 and continue the pattern."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-23-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":40,"display":{"sequence":[10,20,30],"step":10,"promptText":"Identify the rule in 10, 20, 30 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-23-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"What pattern do 6, 12, 18 follow? Continue it."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-23-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":44,"display":{"sequence":[11,22,33],"step":11,"promptText":"Recognize the rule in 11, 22, 33 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-45-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"sequence":[25,50,75],"step":25,"promptText":"Identify the rule in 25, 50, 75 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-45-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"sequence":[12,24,36],"step":12,"promptText":"What pattern do 12, 24, 36 follow? Continue it."}},
  },
  {
    itemId: "skipcounting-conc-patternRule-45-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "patternRule",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":400,"display":{"sequence":[100,200,300],"step":100,"promptText":"Recognize the rule in 100, 200, 300 and find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-K1-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"sequence":[3,6,9],"step":3,"promptText":"What is the step in 3, 6, 9? Use it to find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-K1-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":9,"display":{"sequence":[1,3,5,7],"step":2,"promptText":"Determine the step for 1, 3, 5, 7 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-K1-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":16,"display":{"sequence":[4,8,12],"step":4,"promptText":"Identify the step for 4, 8, 12 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-23-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":28,"display":{"sequence":[7,14,21],"step":7,"promptText":"What is the step in 7, 14, 21? Use it to find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-23-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":32,"display":{"sequence":[8,16,24],"step":8,"promptText":"Determine the step for 8, 16, 24 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-23-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":60,"display":{"sequence":[15,30,45],"step":15,"promptText":"Identify the step for 15, 30, 45 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-45-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":80,"display":{"sequence":[50,60,70],"step":10,"promptText":"What is the step in 50, 60, 70? Use it to find the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-45-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":140,"display":{"sequence":[80,100,120],"step":20,"promptText":"Determine the step for 80, 100, 120 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-stepInference-45-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "stepInference",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":800,"display":{"sequence":[200,400,600],"step":200,"promptText":"Identify the step for 200, 400, 600 and the next term."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-K1-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":15,"display":{"sequence":[5,10],"step":5,"promptText":"Use skip-counting by 5s to find 3 groups of 5."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-K1-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":12,"display":{"sequence":[3,6,9],"step":3,"promptText":"Use skip-counting by 3s for 4 groups of 3."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-K1-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [1,3],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":10,"display":{"sequence":[2,4,6,8],"step":2,"promptText":"Use skip-counting by 2s for 5 groups of 2."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-23-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":20,"display":{"sequence":[4,8,12,16],"step":4,"promptText":"Use skip-counting by 4s for 5 groups of 4."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-23-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":30,"display":{"sequence":[5,10,15,20,25],"step":5,"promptText":"Use skip-counting by 5s for 6 groups of 5."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-23-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [4,6],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":24,"display":{"sequence":[6,12,18],"step":6,"promptText":"Use skip-counting by 6s for 4 groups of 6."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-45-001",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":48,"display":{"sequence":[12,24,36],"step":12,"promptText":"Use skip-counting by 12s for 4 groups of 12."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-45-002",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":100,"display":{"sequence":[25,50,75],"step":25,"promptText":"Use skip-counting by 25s for 4 groups of 25."}},
  },
  {
    itemId: "skipcounting-conc-groupsToProduct-45-003",
    modeId: "skipCounting",
    itemFamily: "conceptual",
    subskill: "groupsToProduct",
    structureType: "patternNext",
    levelRange: [7,10],
    reviewStatus: APPROVED,
    question: {"a":null,"b":null,"op":"skip","answer":54,"display":{"sequence":[9,18,27,36,45],"step":9,"promptText":"Use skip-counting by 9s for 6 groups of 9."}},
  },
];
