export const THEMES = {
  default: {
    id: "default",
    label: "Soft Play",
    emoji: "🌈",
    description: "Pastel colors & friendly vibes",
    bg: "bg-amber-50",
    navBg: "bg-white/80",
    navText: "text-slate-700",
    navActive: "bg-violet-100 text-violet-600",
    navHover: "hover:bg-gray-100 hover:text-slate-700",
    logoPill: "from-pink-400 to-violet-400",
    cardBg: "bg-white/80",
    cardBorder: "border-gray-200",
    textPrimary: "text-slate-700",
    textSecondary: "text-slate-500",
    textMuted: "text-slate-400",
    heroGradient: "from-pink-500 via-violet-500 to-sky-500",
    ctaPrimary: "from-pink-400 to-violet-400",
    ctaSecondary: "bg-white/80 border-gray-200 text-slate-600",
    featureCards: [
      { bg: "bg-pink-50", gradient: "from-pink-300 to-pink-400" },
      { bg: "bg-sky-50", gradient: "from-sky-300 to-sky-400" },
      { bg: "bg-violet-50", gradient: "from-violet-300 to-violet-400" },
    ],
    bubbleColors: [
      "from-pink-300 to-pink-400",
      "from-sky-300 to-sky-400",
      "from-lime-300 to-lime-400",
      "from-violet-300 to-violet-400",
    ],
    modeColors: {
      addition: "bg-pink-400",
      subtraction: "bg-sky-400",
      multiplication: "bg-violet-400",
      division: "bg-amber-400",
      comparing: "bg-teal-400",
      counting: "bg-orange-400",
      skipCounting: "bg-cyan-400",
      placeValue: "bg-rose-400",
    },
    progressTrack: "bg-amber-100 border-amber-200",
    progressFill: "from-amber-300 to-orange-400",
    progressIcon: "text-orange-600",
    stepBg: "bg-amber-100 text-amber-600",
    stepLabel: "text-amber-500",
    worksheetCallout: "from-emerald-50 to-teal-50",
    worksheetCalloutIcon: "text-emerald-500",
    worksheetCalloutBtn: "from-emerald-400 to-teal-400",
    selectedBorder: "border-violet-400 bg-violet-50",
    selectedText: "text-violet-600",
    selectedIcon: "text-violet-500",
    fontClass: "",
    completeMsg: "Amazing!",
  },

  mario: {
    id: "mario",
    label: "Super Mario",
    emoji: "🍄",
    description: "Power-ups & pipes!",
    bg: "bg-sky-100",
    navBg: "bg-red-600/90",
    navText: "text-white",
    navActive: "bg-yellow-400 text-red-700",
    navHover: "hover:bg-red-500 hover:text-white",
    logoPill: "from-red-500 to-yellow-400",
    cardBg: "bg-white/90",
    cardBorder: "border-red-200",
    textPrimary: "text-red-800",
    textSecondary: "text-red-600",
    textMuted: "text-red-400",
    heroGradient: "from-red-500 via-yellow-400 to-green-500",
    ctaPrimary: "from-red-500 to-red-600",
    ctaSecondary: "bg-yellow-300 border-yellow-400 text-red-700",
    featureCards: [
      { bg: "bg-red-50", gradient: "from-red-400 to-red-500" },
      { bg: "bg-green-50", gradient: "from-green-400 to-green-500" },
      { bg: "bg-yellow-50", gradient: "from-yellow-400 to-yellow-500" },
    ],
    bubbleColors: [
      "from-red-400 to-red-500",
      "from-green-400 to-green-500",
      "from-yellow-400 to-yellow-500",
      "from-blue-400 to-blue-500",
    ],
    modeColors: {
      addition: "bg-red-500",
      subtraction: "bg-green-500",
      multiplication: "bg-yellow-500",
      division: "bg-blue-500",
      comparing: "bg-orange-500",
      counting: "bg-purple-500",
      skipCounting: "bg-cyan-500",
      placeValue: "bg-pink-500",
    },
    progressTrack: "bg-green-100 border-green-300",
    progressFill: "from-green-400 to-green-500",
    progressIcon: "text-green-700",
    stepBg: "bg-red-100 text-red-600",
    stepLabel: "text-red-500",
    worksheetCallout: "from-green-50 to-emerald-50",
    worksheetCalloutIcon: "text-green-600",
    worksheetCalloutBtn: "from-green-500 to-green-600",
    selectedBorder: "border-red-400 bg-red-50",
    selectedText: "text-red-600",
    selectedIcon: "text-red-500",
    fontClass: "font-mario",
    completeMsg: "Wahoo!",
  },

  zelda: {
    id: "zelda",
    label: "Adventure Quest",
    emoji: "⚔️",
    description: "Explore the math kingdom!",
    bg: "bg-emerald-50",
    navBg: "bg-emerald-800/90",
    navText: "text-emerald-100",
    navActive: "bg-yellow-400 text-emerald-900",
    navHover: "hover:bg-emerald-700 hover:text-white",
    logoPill: "from-emerald-500 to-yellow-400",
    cardBg: "bg-white/85",
    cardBorder: "border-emerald-200",
    textPrimary: "text-emerald-900",
    textSecondary: "text-emerald-700",
    textMuted: "text-emerald-500",
    heroGradient: "from-emerald-500 via-teal-400 to-yellow-400",
    ctaPrimary: "from-emerald-500 to-emerald-600",
    ctaSecondary: "bg-yellow-200 border-yellow-300 text-emerald-800",
    featureCards: [
      { bg: "bg-emerald-50", gradient: "from-emerald-400 to-emerald-500" },
      { bg: "bg-teal-50", gradient: "from-teal-400 to-teal-500" },
      { bg: "bg-yellow-50", gradient: "from-yellow-400 to-amber-500" },
    ],
    bubbleColors: [
      "from-emerald-400 to-emerald-500",
      "from-teal-400 to-teal-500",
      "from-yellow-400 to-amber-500",
      "from-sky-400 to-sky-500",
    ],
    modeColors: {
      addition: "bg-emerald-500",
      subtraction: "bg-teal-500",
      multiplication: "bg-yellow-500",
      division: "bg-sky-500",
      comparing: "bg-amber-500",
      counting: "bg-rose-500",
      skipCounting: "bg-cyan-500",
      placeValue: "bg-violet-500",
    },
    progressTrack: "bg-yellow-100 border-yellow-300",
    progressFill: "from-yellow-300 to-amber-400",
    progressIcon: "text-amber-600",
    stepBg: "bg-emerald-100 text-emerald-700",
    stepLabel: "text-emerald-600",
    worksheetCallout: "from-yellow-50 to-amber-50",
    worksheetCalloutIcon: "text-amber-600",
    worksheetCalloutBtn: "from-emerald-500 to-emerald-600",
    selectedBorder: "border-emerald-400 bg-emerald-50",
    selectedText: "text-emerald-600",
    selectedIcon: "text-emerald-500",
    fontClass: "font-zelda",
    completeMsg: "Triforce Complete!",
  },

  minecraft: {
    id: "minecraft",
    label: "Block Builder",
    emoji: "⛏️",
    description: "Mine your way through math!",
    bg: "bg-stone-100",
    navBg: "bg-stone-800/90",
    navText: "text-stone-200",
    navActive: "bg-lime-400 text-stone-900",
    navHover: "hover:bg-stone-700 hover:text-white",
    logoPill: "from-lime-500 to-emerald-600",
    cardBg: "bg-stone-50/90",
    cardBorder: "border-stone-300",
    textPrimary: "text-stone-800",
    textSecondary: "text-stone-600",
    textMuted: "text-stone-500",
    heroGradient: "from-lime-500 via-emerald-500 to-stone-600",
    ctaPrimary: "from-lime-500 to-emerald-600",
    ctaSecondary: "bg-stone-200 border-stone-300 text-stone-700",
    featureCards: [
      { bg: "bg-lime-50", gradient: "from-lime-400 to-lime-500" },
      { bg: "bg-amber-50", gradient: "from-amber-500 to-amber-600" },
      { bg: "bg-cyan-50", gradient: "from-cyan-400 to-cyan-500" },
    ],
    bubbleColors: [
      "from-lime-400 to-lime-500",
      "from-amber-500 to-amber-600",
      "from-cyan-400 to-cyan-500",
      "from-stone-400 to-stone-500",
    ],
    modeColors: {
      addition: "bg-lime-500",
      subtraction: "bg-amber-500",
      multiplication: "bg-cyan-500",
      division: "bg-emerald-500",
      comparing: "bg-orange-500",
      counting: "bg-sky-500",
      skipCounting: "bg-teal-500",
      placeValue: "bg-rose-500",
    },
    progressTrack: "bg-lime-100 border-lime-300",
    progressFill: "from-lime-400 to-emerald-500",
    progressIcon: "text-lime-700",
    stepBg: "bg-stone-200 text-stone-700",
    stepLabel: "text-stone-600",
    worksheetCallout: "from-lime-50 to-emerald-50",
    worksheetCalloutIcon: "text-lime-600",
    worksheetCalloutBtn: "from-lime-500 to-emerald-600",
    selectedBorder: "border-lime-400 bg-lime-50",
    selectedText: "text-lime-600",
    selectedIcon: "text-lime-500",
    fontClass: "font-minecraft",
    completeMsg: "Crafted It!",
  },
};

export const THEME_IDS = Object.keys(THEMES);

export function getTheme(id) {
  return THEMES[id] || THEMES.default;
}
